window.figures3 = [


{series:"wanpi", name:"ワンピース KING OF ARTIST ROB LUCCI Awakening-SPECIAL ver.-", search:"ろぶるっち　ロブルッチ", type:"koa", price:600, date:"2026-06-03", img:"images/wanpi/rutti_koa_sp.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"サルゲッチュ モニタートップフィギュア～ピポサル～", search:"ぴぽざる", type:"moni", price:600, date:"2026-06-03", img:"images/sonota/saru_pure.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"サルゲッチュ モニタートップフィギュア～ピポサル～", search:"ぴぽざる", type:"moni", price:600, date:"2026-06-03", img:"images/sonota/saru_pure2.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦懐玉・玉折FIGURIZMα“五条悟”術式反転「赫」", search:"ごじょうさとる", type:"fig", price:1100, date:"1899-12-30", img:"images/zyuzyutu/aka_fig.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 VIBRATION STARS PLUS-竈門炭治郎-", search:"かまどたんじろう", type:"vib", price:1300, date:"1899-12-30", img:"images/kimetu/tan_vib_p.jpg", source:"https://bsp-prize.jp/"},
{series:"tyen", name:"チェンソーマン おおきなSOFVIMATES～ポチタは泣きながら俺を待っていた～", search:"ぽちた", type:"sof", price:5000, date:"1899-12-30", img:"images/tyen/potita_naki.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん -俺のフィギュア 野原ひろし-", search:"のはらひろし", type:"", price:800, date:"1899-12-30", img:"images/kuresin/hirosi.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース フィグライフ! モンキー・D・ルフィ-ギア5-vol.3", search:"にか　ニカ　ルフィ　るふぃ", type:"figl", price:1000, date:"1899-12-30", img:"images/wanpi/nika_figl3.jpg", source:"https://bsp-prize.jp/"},
{series:"sakamoto", name:"SAKAMOTODAYSLuminasta“坂本太郎”本気Ver.", search:"さかもとたろう", type:"lum", price:400, date:"1899-12-30", img:"images/sakamoto/sakamoto_honki_lum.jpg", source:"https://segaplaza.jp/"},
{series:"db", name:"ドラゴンボール超 BLOOD OF SAIYANS-ゴジータ&ベジット-", search:"ごじーた", type:"blood", price:500, date:"1899-12-30", img:"images/db/gozi_blood.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 BLOOD OF SAIYANS-ゴジータ&ベジット-", search:"べじっと", type:"blood", price:600, date:"1899-12-30", img:"images/db/bezitto_blood.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 BLOOD OF SAIYANS-ベジータ-", search:"べじーた", type:"blood", price:600, date:"1899-12-30", img:"images/db/bezi_blood.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 MATCH MAKERS 超サイヤ人ゴッド孫悟空（VSビルス）", search:"そんごくう", type:"mat", price:500, date:"1899-12-30", img:"images/db/goku_mat_birusu.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 MATCH MAKERS ビルス（VS超サイヤ人ゴッド孫悟空）", search:"びるす", type:"mat", price:500, date:"1899-12-30", img:"images/db/birusu_mat_goku.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～SPECIAL MONKEY.D.GARP", search:"モンキーディーガープ　もんきーでぃーがーぷ", type:"dxf", price:800, date:"1899-12-30", img:"images/wanpi/gapu_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～SPECIAL NEFELTARI VIVI", search:"ネフェルタリビビ　ねふぇるたりびび", type:"dxf", price:500, date:"1899-12-30", img:"images/wanpi/bibi_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～SPECIAL MONKEY.D.LUFFY", search:"るふぃ　ルフィ", type:"dxf", price:700, date:"1899-12-30", img:"images/wanpi/rufi_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"pro", name:"プロジェクトセカイカラフルステージ！feat.初音ミク Desktop×DecorateCollections “天馬咲希”", search:"てんまさき", type:"ddc", price:650, date:"1899-12-30", img:"images/pro/tenma_ddc.jpg", source:"https://segaplaza.jp/"},
{series:"wanpi", name:"ワンピース Q posket-ヤマト-", search:"やまと", type:"qpos", price:300, date:"1899-12-30", img:"images/wanpi/yamato_qpos.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース フィグライフ! モンキー・D・ルフィ-ギア5-vol.2", search:"にか　ニカ　ルフィ　るふぃ", type:"figl", price:800, date:"1899-12-30", img:"images/wanpi/nika_figl2.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～JEWELRY.BONNEY CHILDREN ver.", search:"ジュエリーボニー　じゅえりーぼにー", type:"dxf", price:400, date:"1899-12-30", img:"images/wanpi/boni_dxf_child.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"『ONE PIECE FILM RED』 Q posket-UTA-", search:"ウタ　うた", type:"qpos", price:300, date:"1899-12-30", img:"images/wanpi/uta_qpos.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"『ONE PIECE FILM RED』 DXF～THE GRANDLINE LADY～vol.1", search:"ウタ　うた", type:"dxf", price:400, date:"1899-12-30", img:"images/wanpi/uta_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"『ONE PIECE FILM RED』 DXF～THE GRANDLINE SERIES～UTA CHILDREN", search:"ウタ　うた", type:"dxf", price:300, date:"1899-12-30", img:"images/wanpi/uta_dxf_child.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース サボ ルームライト-火拳（ヒケン）-", search:"さぼ　ひけん", type:"", price:400, date:"1899-12-30", img:"images/wanpi/hiken_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース トラファルガー・ロー ルームライト-R・ROOM“凪（サイレント）”-", search:"とらふぁるがーろー　るーむさいれんと", type:"", price:500, date:"1899-12-30", img:"images/wanpi/sairento_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん おおきなSOFVIMATES～野原しんのすけ（ワニ山さんver.）～パステルカラーver.", search:"のはらしんのすけ", type:"sof", price:500, date:"1899-12-30", img:"images/kuresin/wani_sof.jpg", source:"https://bsp-prize.jp/"},    
{series:"osinoko", name:"【推しの子】 全力造形 フィギュア MEMちょ", search:"めむちょ", type:"zenryoku", price:300, date:"1899-12-30", img:"images/osinoko/memu_zen.jpg", source:"http://www.fans.co.jp/"},
{series:"oba", name:"オーバーロード　Desktop Cute フィギュア　アルベド～牛柄水着ver.～Renewal", search:"あるべど", type:"desk", price:500, date:"1899-12-30", img:"images/oba/aru_usi_re.jpg", source:"https://www.taito.co.jp/"},
{series:"wanpi", name:"ワンピース BATTLE RECORD COLLECTION-MONKEY.D.GARP-", search:"もんきーでぃーがーぷ　モンキーディーガープ", type:"bato", price:600, date:"1899-12-30", img:"images/wanpi/gapu_bato1.jpg", source:"https://bsp-prize.jp/"},
{series:"crazy", name:"Crazy Raccoon デスクトップフィギュア-VanilLa-", search:"ばにら　バニラ", type:"moni", price:400, date:"1899-12-30", img:"images/crazy/banira.jpg", source:"https://bsp-prize.jp/"},
{series:"crazy", name:"Crazy Raccoon デスクトップフィギュア-VanilLa-", search:"ばにら　バニラ", type:"moni", price:400, date:"1899-12-30", img:"images/crazy/banira_b.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～ポムポムプリン リラックスver.～", search:"ぽむぽむぷりん", type:"sof", price:500, date:"1899-12-30", img:"images/sanrio/pom_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"togen", name:"桃源暗鬼 むっくんスピーカー", search:"", type:"", price:500, date:"1899-12-30", img:"images/togen/mukkun.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～ポチャッコ リラックスver.～", search:"ぽちゃっこ", type:"sof", price:600, date:"1899-12-30", img:"images/sanrio/po_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"Netflixシリーズ「My Melody & Kuromi」 Fluffy Puffy～My Melody & Kuromi～", search:"くろみ", type:"flu", price:700, date:"1899-12-30", img:"images/sanrio/kuro_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～ハローキティ＆シナモロール～", search:"はろーきてぃ", type:"flu", price:800, date:"1899-12-30", img:"images/sanrio/kitesina_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～ハローキティ＆シナモロール～", search:"しなもろーる", type:"flu", price:800, date:"1899-12-30", img:"images/sanrio/sinakite_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～マイメロディ＆クロミ～", search:"まいめろでぃ", type:"flu", price:600, date:"1899-12-30", img:"images/sanrio/maikuro_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～マイメロディ＆クロミ～", search:"くろみ", type:"flu", price:700, date:"1899-12-30", img:"images/sanrio/kuromai_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_a.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_b.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_c.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_d.jpg", source:"https://bsp-prize.jp/"},
{series:"holo", name:"ホロライブプロダクション ひっかけフィギュアVol.11", search:"不知火フレア　しらぬいふれあ", type:"hikkake", price:200, date:"1899-12-30", img:"images/holo/furea_11.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブプロダクション ひっかけフィギュアVol.11", search:"白銀ノエル　しろがねのえる", type:"hikkake", price:200, date:"1899-12-30", img:"images/holo/noeru_11.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブプロダクション ひっかけフィギュアVol.11", search:"博衣こより　はくいこより", type:"hikkake", price:200, date:"1899-12-30", img:"images/holo/koyori_11.jpg", source:"https://charahiroba.com/"},
{series:"mar", name:"MARVELACT/CUTプレミアムフィギュア“シング”", search:"しんぐ", type:"act", price:400, date:"1899-12-30", img:"images/mar/thing_act.jpg", source:"https://segaplaza.jp/"},
{series:"furi-ren", name:"葬送のフリーレン フィギュアライト フリーレン-ゾルトラーク-", search:"ふりーれん　ぞるとらーく", type:"", price:800, date:"1899-12-30", img:"images/furi-ren/furizoru_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"wnapi", name:"ワンピース THE出航-NAMI-ver.EGGHEAD", search:"なみ", type:"syukko", price:800, date:"1899-12-30", img:"images/wanpi/nami_syukko_egg.jpg", source:"https://bsp-prize.jp/"},
{series:"amagamisan", name:"甘神さんちの縁結び　Coreful フィギュア　甘神夜重", search:"あまがみやえ", type:"core", price:300, date:"1899-12-30", img:"images/amagamisan/yae_core.jpg", source:"https://www.taito.co.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“江戸川コナン”", search:"えどがわこなん", type:"peti", price:400, date:"1899-12-30", img:"images/konan/konan_peti.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“灰原哀”", search:"はいばらあい", type:"peti", price:400, date:"1899-12-30", img:"images/konan/ai_peti.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“工藤新一”", search:"くどうしんいち", type:"peti", price:400, date:"1899-12-30", img:"images/konan/sin_peti.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“毛利蘭”", search:"もうりらん", type:"peti", price:400, date:"1899-12-30", img:"images/konan/ran_peti.jpg", source:"https://segaplaza.jp/"},
{series:"gotoyome", name:"五等分の花嫁＊ 中野一花フィギュア五等分の花嫁アニメ原画展ver.", search:"なかのいちか", type:"", price:300, date:"1899-12-30", img:"images/gotoyome/itika_genga.jpg", source:"https://bsp-prize.jp/"},
{series:"oba", name:"オーバーロード IF-Relax time-アルベド", search:"あるべど", type:"relax", price:550, date:"1899-12-30", img:"images/oba/aru_relax_if.jpg", source:"https://bsp-prize.jp/"},
{series:"sasa", name:"ささやくように恋を唄うちょこのせプレミアムフィギュア“朝凪依”", search:"あさなぎより", type:"tyoko", price:300, date:"1899-12-30", img:"images/sasa/asa_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"sasa", name:"ささやくように恋を唄うちょこのせプレミアムフィギュア“木野ひまり”", search:"きのひまり", type:"tyoko", price:300, date:"1899-12-30", img:"images/sasa/kino_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 フィギュアライト 冨岡義勇-水の呼吸-", search:"とみおかぎゆう　みずのこきゅう", type:"", price:800, date:"2026-06-04", img:"images/kimetu/giyu_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"death", name:"DEATH NOTE　ぬーどるストッパーフィギュアーLー", search:"える　", type:"nusuto", price:1000, date:"2026-06-05", img:"images/death/l_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"wanpi", name:"ワンピース BATTLE RECORD COLLECTION-BARTHOLOMEW.KUMA-", search:"バーソロミューくま　ばーそろみゅーくま", type:"", price:800, date:"2026-06-03", img:"images/wanpi/kuma_bato.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"初音ミク　Trio-Try-iT Figureーレイニーダンスー", search:"はつねみく　れいにーだんす", type:"trio", price:1000, date:"2026-06-04", img:"images/miku/ame_trio.jpg", source:"https://charahiroba.com/"},
{series:"db", name:"ドラゴンボール超 SOLID EDGE WORKS-THE出陣-ゴールデンフリーザ", search:"ごーるでんふりーざ", type:"syutu", price:800, date:"2026-06-03", img:"images/db/gorufuri_syutu.jpg", source:"https://bsp-prize.jp/"},
{series:"dorakue", name:"ドラゴンクエスト　AM　ポケットティッシュケース　ミイラ男＆マミー", search:"みいらおとこ", type:"", price:600, date:"2026-05-23", img:"images/dorakue/mira_a.jpg", source:"https://www.taito.co.jp/"},
{series:"dorakue", name:"ドラゴンクエスト　AM　ポケットティッシュケース　ミイラ男＆マミー", search:"まみー", type:"", price:600, date:"2026-05-23", img:"images/dorakue/mira_b.jpg", source:"https://www.taito.co.jp/"},
{series:"vsupo", name:"ぶいすぽっ！スケールフィギュア-Play with paint-vol.9", search:"夢野あかり　ゆめのあかり", type:"", price:800, date:"2026-05-22", img:"images/vsupo/akari_gigo.jpg", source:"https://www.gigo.co.jp/prizes"},
{series:"konan", name:"名探偵コナンちょこのせプレミアムフィギュア“怪盗キッド”～寝そべりVer.～", search:"かいとうきっど", type:"tyoko", price:600, date:"1899-12-30", img:"images/konan/kiddo_ne_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"mazyotabi", name:"魔女の旅々　Desktop Cute フィギュア　イレイナ～私服ver.～Renewal", search:"いれいな", type:"desk", price:800, date:"1899-12-30", img:"images/mazyotabi/sifuku_desk_re.jpg", source:"https://www.taito.co.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～ララ～", search:"らら", type:"sof", price:500, date:"1899-12-30", img:"images/sanrio/rara_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～キキ～", search:"きき", type:"sof", price:500, date:"1899-12-30", img:"images/sanrio/kiki_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"haikyu", name:"ハイキュー‼ すやすやルームライト-日向翔陽-", search:"ひなたしょうよう", type:"", price:800, date:"1899-12-30", img:"images/haikyu/hinata_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"ozya", name:"おジャ魔女どれみ Paldolce collection Grande-春風どれみ-", search:"はるかぜどれみ", type:"", price:300, date:"1899-12-30", img:"images/ozya/doremi.jpg", source:"https://bsp-prize.jp/"},
{series:"gegege", name:"映画「鬼太郎誕生 ゲゲゲの謎」　Vivitフィギュア ねこ娘", search:"ねこむすめ", type:"vivi", price:300, date:"1899-12-30", img:"images/gegege/neko_vivi.jpg", source:"http://www.fans.co.jp/"},
{series:"nyanko", name:"にゃんこ大戦争 にゃんこ軍団出陣フィギュア～超極ネコ祭 厄災の子キャスリィ～", search:"やくさいのこきゃすりぃ", type:"", price:500, date:"1899-12-30", img:"images/nyanko/kyasu.jpg", source:"https://bsp-prize.jp/"},
{series:"pawapuro", name:"パワフルプロ野球&プロ野球スピリッツ プライズボブルヘッドコレクション", search:"パワプロくん　ぱわぷろくん", type:"", price:500, date:"2026-05-28", img:"images/pawapuro/pawa_bobu.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"pawapuro", name:"パワフルプロ野球&プロ野球スピリッツ プライズボブルヘッドコレクション", search:"ちょうしくん　調子くん", type:"", price:500, date:"2026-05-28", img:"images/pawapuro/tyousi_bobu.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"zyuzyutu", name:"呪術廻戦 KING OF ARTIST GOJO・GETO-懐玉・玉折-SPECIAL ver.", search:"げとうすぐる　夏油傑", type:"koa", price:1100, date:"1899-12-30", img:"images/zyuzyutu/geto_koa_sp.jpg", source:"https://bsp-prize.jp/"},
{series:"kaizyu", name:"怪獣８号　TOONIZEー怪獣８号ー", search:"かいじゅう8ごう", type:"", price:400, date:"1899-12-30", img:"images/kaizyu/kaizyu_too_a.jpg", source:"https://charahiroba.com/"},
{series:"tensura", name:"転生したらスライムだった件 EXQ フィギュア～リムル＝テンペスト～-metallic color version-", search:"りむるてんぺすと", type:"exq", price:1000, date:"1899-12-30", img:"images/tensura/rimuru_exq_namco.jpg", source:"https://bsp-prize.jp/"},
{series:"puniru", name:"Trio-Try-iT Figure ー いつものかわいいぷにる ー", search:"", type:"trio", price:400, date:"1899-12-30", img:"images/puniru/puniru_trio.jpg", source:"https://charahiroba.com/"},
{series:"deara", name:"デート・ア・ライブV BiCute Bunnies Figureー星宮六喰ー", search:"ほしみやむくろ", type:"bani", price:500, date:"1899-12-30", img:"images/deara/mukuro_bani.jpg", source:"https://charahiroba.com/"},
{series:"dandadan", name:"TVアニメ『ダンダダン』Luminasta “モモ”Vol.2Ver.1.5", search:"もも", type:"lum", price:500, date:"1899-12-30", img:"images/dandadan/momo_lum1.5.jpg", source:"https://segaplaza.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ネネちゃんと", search:"野原しんのすけ　のはらしんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinnene_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ネネちゃんと", search:"ネネちゃん　ねねちゃん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/nenesin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ボーちゃんと", search:"野原しんのすけ　のはらしんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinbou_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ボーちゃんと", search:"ボーちゃん　ぼーちゃん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/bousin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～風間くんと", search:"のはらしんのすけ　野原しんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinkaza_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～風間くんと", search:"風間くん　かざまくん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/kazasin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～へびしんちゃんとうましんちゃん～", search:"のはらしんのすけ　野原しんのすけ", type:"", price:500, date:"1899-12-30", img:"images/kuresin/hebi.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～へびしんちゃんとうましんちゃん～", search:"のはらしんのすけ　野原しんのすけ", type:"", price:500, date:"1899-12-30", img:"images/kuresin/uma.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ Q posket-佐野万次郎-私服ver.", search:"さのまんじろう　マイキー　まいきー", type:"qpos", price:300, date:"1899-12-30", img:"images/toribe/maiki_qpos_sifuku.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ Q posket-佐野万次郎-私服ver.", search:"さのまんじろう　マイキー　まいきー", type:"qpos", price:300, date:"1899-12-30", img:"images/toribe/maiki_qpos_sifuku_b.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース THE出航-SABO-", search:"サボ　さぼ", type:"syukko", price:500, date:"1899-12-30", img:"images/wanpi/sabo1_syukko.jpg", source:"https://bsp-prize.jp/"},
{series:"spy", name:"SPY×FAMILY Q posket-アーニャ・フォージャー-Ⅲ", search:"あーにゃふぉーじゃー", type:"qpos", price:300, date:"1899-12-30", img:"images/spy/anya3_qpos.jpg", source:"https://bsp-prize.jp/"},
{series:"spy", name:"SPY×FAMILY Q posket-アーニャ・フォージャー-Ⅲ", search:"あーにゃふぉーじゃー", type:"qpos", price:300, date:"1899-12-30", img:"images/spy/anya3_qpos_b.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～EXTRA KING", search:"キング　きんぐ", type:"dxf", price:500, date:"1899-12-30", img:"images/wanpi/king_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"aimasu", name:"アイドルマスター ミリオンライブ！-Celestial vivi-如月千早", search:"きさらぎちはや", type:"cele", price:400, date:"1899-12-30", img:"images/aimasu/tihaya_cele.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ プレミアムフィギュア“乾青宗”-黒龍-", search:"いぬいせいしゅう", type:"", price:300, date:"1899-12-30", img:"images/toribe/inui.jpg", source:"https://segaplaza.jp/"},
{series:"toribe", name:"東京リベンジャーズ　九井一フィギュア", search:"ここのいはじめ", type:"", price:300, date:"1899-12-30", img:"images/toribe/kokonoi.jpg", source:"https://www.taito.co.jp/"},
{series:"kinniku", name:"キン肉マン サウナフィギュア-テリーマン-", search:"てりーまん", type:"", price:300, date:"1899-12-30", img:"images/kinniku/teri_sauna.jpg", source:"https://bsp-prize.jp/"},
{series:"kinniku", name:"キン肉マン サウナフィギュア-キン肉マン-", search:"きんにくまん", type:"", price:600, date:"1899-12-30", img:"images/kinniku/kin_sauna.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】　Vivitフィギュア アイ チアリーディングVer.", search:"あい", type:"vivi", price:500, date:"1899-12-30", img:"images/osinoko/ai_vivi.jpg", source:"http://www.fans.co.jp/"},
{series:"oba", name:"オーバーロード IFアルベドフィギュア-teacher style ver.-", search:"あるべど", type:"", price:500, date:"1899-12-30", img:"images/oba/aru_tea.jpg", source:"https://bsp-prize.jp/"},
{series:"deara", name:"デート・ア・ライブ GLITTER&GLAMOURS-KURUMI TOKISAKI-", search:"ときさきくるみ", type:"gli", price:400, date:"1899-12-30", img:"images/deara/kurumi_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"witti", name:"TVアニメ『ウィッチウォッチ』　浴衣フィギュア 若月ニコ", search:"わかつきにこ", type:"", price:300, date:"1899-12-30", img:"images/witti/niko_yukata.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"witti", name:"TVアニメ『ウィッチウォッチ』　浴衣フィギュア 宮尾音夢", search:"みやおねむ", type:"", price:300, date:"1899-12-30", img:"images/witti/nemu_yukata.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"sao", name:"ソードアート・オンライン BiCute Bunnies Figureーアスナー", search:"あすな", type:"bani", price:600, date:"1899-12-30", img:"images/sao/asuna_bani.jpg", source:"https://charahiroba.com/"},
{series:"100kano", name:"君のことが大大大大大好きな100人の彼女 -Relax time-花園羽香里", search:"はなぞのはかり", type:"relax", price:1000, date:"1899-12-30", img:"images/100kano/hana_relax.jpg", source:"https://bsp-prize.jp/"},
{series:"konosuba", name:"この素晴らしい世界に祝福を！３　Coreful フィギュア　ダクネス～水着ver.～", search:"だくねす", type:"core", price:900, date:"1899-12-30", img:"images/konosuba/daku_core_mizugi.jpg", source:"https://www.taito.co.jp/"},
{series:"spy", name:"SPY×FAMILY　Trio－Try－iT Figureーアーニャ・フォージャーー", search:"あーにゃふぉーじゃー", type:"trio", price:500, date:"1899-12-30", img:"images/spy/anya_trio.jpg", source:"https://charahiroba.com/"},
{series:"kimetu", name:"「鬼滅の刃」　FIGURIZMα　“甘露寺蜜璃”", search:"かんろじみつり", type:"fig", price:1300, date:"1899-12-30", img:"images/kimetu/kanrozi_fig.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 MAXIMATIC THE MITSURI KANROJI", search:"かんろじみつり", type:"ma", price:1700, date:"1899-12-30", img:"images/kimetu/kanrozi_ma.jpg", source:"https://bsp-prize.jp/"},
{series:"botti", name:"アニメ「ぼっち・ざ・ろっく！」 伊地知虹夏 フィギュア vol.2", search:"いじちにじか", type:"", price:600, date:"1899-12-30", img:"images/botti/nizika2.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】　Aqua Float Girls フィギュア　アイ", search:"あい", type:"aqua", price:900, date:"1899-12-30", img:"images/osinoko/ai_aqua.jpg", source:"https://www.taito.co.jp/"},
{series:"atorie", name:"アニメ『ライザのアトリエ ～常闇の女王と秘密の隠れ家～』　Coreful フィギュア　ライザ～水着ver.～", search:"らいざ", type:"core", price:600, date:"1899-12-30", img:"images/atorie/raiza_core_mizugi.jpg", source:"https://www.taito.co.jp/"},
{series:"sonota", name:"勇気爆発バーンブレイバーン Break time collection vol.1", search:"ゆうきばくはつばーんぶれいばーん", type:"bre", price:300, date:"1899-12-30", img:"images/sonota/ban_bre.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース フィグライフ! モンキー・D・ルフィ-ギア5-vol.4", search:"るふぃ　ニカ　にか", type:"figl", price:400, date:"1899-12-30", img:"images/wanpi/nika_figl4.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】 アイ-サインはB-フィギュア", search:"あい", type:"", price:600, date:"1899-12-30", img:"images/osinoko/ai_b.jpg", source:"https://bsp-prize.jp/"},
{series:"eva", name:"シン・エヴァンゲリオン劇場版Luminasta“真希波・マリ・イラストリアス”", search:"まきなみまりいらすとりあす", type:"lum", price:800, date:"1899-12-30", img:"images/eva/mari_lum.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"鬼滅の刃 ぬーどるストッパーフィギュア ―伊黒小芭内―", search:"いぐろおばない", type:"nusuto", price:4500, date:"1899-12-30", img:"images/kimetu/iguro_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"zyuzyutu", name:"呪術廻戦懐玉・玉折FIGURIZMα“五条悟”覚醒", search:"ごじょうさとる", type:"fig", price:1300, date:"1899-12-30", img:"images/zyuzyutu/gozyo_kakusei.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"鬼滅の刃　プレミアムちょこのせフィギュア“煉󠄁獄杏寿郎”", search:"れんごくきょうじゅろう", type:"tyoko", price:800, date:"1899-12-30", img:"images/kimetu/rengoku_tyoko_oni.jpg", source:"https://segaplaza.jp/"},
{series:"mazyotabi", name:"魔女の旅々　AMP＋ イレイナ フィギュア～魔女服ver.～", search:"いれいな", type:"amp", price:1000, date:"1899-12-30", img:"images/mazyotabi/amp.jpg", source:"https://www.taito.co.jp/"},
{series:"naruto", name:"NARUTO-ナルト- BANPRESTO FIGURE COLOSSEUM 造形忍界大戦 ロック・リー", search:"ろっくりー", type:"ninkai", price:2300, date:"1899-12-30", img:"images/naruto/ri_ninkai.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース THE出航-NAMI-", search:"なみ　ナミ", type:"syukko", price:500, date:"1899-12-30", img:"images/wanpi/nami_syukko.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～マイメロディ・クロミ～", search:"まいめろでぃ", type:"", price:500, date:"2026-05-27", img:"images/sanrio/maimero_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～マイメロディ・クロミ～", search:"くろみ", type:"", price:500, date:"2026-05-27", img:"images/sanrio/kuromi_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 鎮座獣 コイン怪獣カネゴン", search:"こいんかいじゅうかねごん", type:"tinza", price:500, date:"2026-05-27", img:"images/uru/kane_tinza.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 鎮座獣 コイン怪獣カネゴン", search:"こいんかいじゅうかねごん", type:"tinza", price:500, date:"2026-05-27", img:"images/uru/kane_tinza_b.jpg", source:"https://bsp-prize.jp/"},
{series:"monhan", name:"モンスターハンター 鎮座獣 アルシュベルド～夢から覚めて～", search:"あるしゅべると", type:"tinza", price:400, date:"2026-05-27", img:"images/monhan/arusyu_tinza.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"Trio-Try-iT Figureージジ(変身)ー", search:"じじ", type:"trio", price:500, date:"2026-05-27", img:"images/dandadan/zizi_trio.jpg", source:"https://charahiroba.com/"},
{series:"umamusume", name:"Trio-Try-iT Figure―ヒシミラクルー", search:"ひしみらくる", type:"trio", price:700, date:"2026-05-27", img:"images/umamusume/hisi_trio.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブ #hololive IF -ホロベイビーズ-宝鐘マリン", search:"ほうしょうまりん", type:"", price:500, date:"2026-05-26", img:"images/holo/marin_baby.jpg", source:"https://bsp-prize.jp/"},
{series:"holo", name:"ホロライブ #hololive IF -ホロベイビーズ-こぼ・かなえる", search:"", type:"", price:500, date:"2026-05-26", img:"images/holo/kobo_baby.jpg", source:"https://bsp-prize.jp/"},
{series:"king", name:"キングダム オギコフィギュア", search:"おぎこ", type:"", price:500, date:"2026-05-27", img:"images/king/ogiko.jpg", source:"https://bsp-prize.jp/"},
{series:"tomuzyeri", name:"トムとジェリー ビッグソフビフィギュア-Yummy Bread-", search:"じぇりー　たふぃー　ジェリー　タフィー", type:"", price:500, date:"2026-05-27", img:"images/tomuzyeri/zyeritafi.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"UNIVERSAL おおきなSOFVIMATES～おさるのジョージ～", search:"おさるのじょーじ", type:"sof", price:400, date:"2026-05-26", img:"images/sonota/zyozi_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"TVアニメ『ダンダダン』 フィグライフ!モモ", search:"もも", type:"figl", price:400, date:"2026-05-26", img:"images/dandadan/momo_figl.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"初音ミクシリーズ　Luminasta　“初音ミク 16th Anniversary”KEI Ver.", search:"はつねみく", type:"lum", price:700, date:"1899-12-30", img:"images/miku/16_key.jpg", source:"https://segaplaza.jp/"},
{series:"db", name:"ドラゴンボールZ MATCH MAKERS 魔人ブウ（VS超サイヤ人3孫悟空）", search:"まじんぶう", type:"mat", price:600, date:"1899-12-30", img:"images/db/bu_mat_goku.jpg", source:"https://bsp-prize.jp/"},
{series:"king", name:"キングダム Grandistaｰ桓騎ｰ", search:"かんき", type:"gra", price:500, date:"2026-05-27", img:"images/king/kanki_gra.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュアvol.3", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"1899-12-30", img:"images/kuresin/kosu_buri.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュアvol.3", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"1899-12-30", img:"images/kuresin/kosu_kan.jpg", source:"https://bsp-prize.jp/"},
{series:"konan", name:"名探偵コナン XrossLink フィギュア“江戸川コナン”", search:"えどがわこなん", type:"xros", price:400, date:"1899-12-30", img:"images/konan/konan_xros.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナン XrossLink フィギュア“怪盗キッド”", search:"かいとうきっど", type:"xros", price:700, date:"1899-12-30", img:"images/konan/kiddo_xros.jpg", source:"https://segaplaza.jp/"},
{series:"gorukamu", name:"TVアニメ『ゴールデンカムイ』XrossLinkフィギュア“白石由竹”", search:"しらいしよしたけ", type:"xros", price:300, date:"1899-12-30", img:"images/gorukamu/siraisi_xros.jpg", source:"https://segaplaza.jp/"},
];
