window.figures3 = [





{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ネネちゃんと", search:"野原しんのすけ　のはらしんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinnene_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ネネちゃんと", search:"ネネちゃん　ねねちゃん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/nenesin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ボーちゃんと", search:"野原しんのすけ　のはらしんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinbou_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ボーちゃんと", search:"ボーちゃん　ぼーちゃん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/bousin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～風間くんと", search:"のはらしんのすけ　野原しんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinkaza_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～風間くんと", search:"風間くん　かざまくん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/kazasin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～へびしんちゃんとうましんちゃん～", search:"のはらしんのすけ　野原しんのすけ", type:"", price:500, date:"1899-12-30", img:"images/kuresin/hebi.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～へびしんちゃんとうましんちゃん～", search:"のはらしんのすけ　野原しんのすけ", type:"", price:500, date:"1899-12-30", img:"images/kuresin/uma.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ Q posket-佐野万次郎-私服ver.", search:"さのまんじろう　マイキー　まいきー", type:"qpos", price:300, date:"1899-12-30", img:"images/toribe/maiki_qpos_sifuku.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ Q posket-佐野万次郎-私服ver.", search:"さのまんじろう　マイキー　まいきー", type:"qpos", price:300, date:"1899-12-30", img:"images/toribe/maiki_qpos_sifuku_b.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース THE出航-SABO-", search:"サボ　さぼ", type:"syukko", price:500, date:"1899-12-30", img:"images/wanpi/sabo1_syukko.jpg", source:"https://bsp-prize.jp/"},
{series:"spy", name:"SPY×FAMILY Q posket-アーニャ・フォージャー-Ⅲ", search:"あーにゃふぉーじゃー", type:"qpos", price:300, date:"1899-12-30", img:"images/spy/anya3_qpos.jpg", source:"https://bsp-prize.jp/"},
{series:"spy", name:"SPY×FAMILY Q posket-アーニャ・フォージャー-Ⅲ", search:"あーにゃふぉーじゃー", type:"qpos", price:300, date:"1899-12-30", img:"images/spy/anya3_qpos_b.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～EXTRA KING", search:"キング　きんぐ", type:"dxf", price:500, date:"1899-12-30", img:"images/wanpi/king_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"aimasu", name:"アイドルマスター ミリオンライブ！-Celestial vivi-如月千早", search:"きさらぎちはや", type:"cele", price:400, date:"1899-12-30", img:"images/aimasu/tihaya_cele.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ プレミアムフィギュア“乾青宗”-黒龍-", search:"いぬいせいしゅう", type:"", price:300, date:"1899-12-30", img:"images/toribe/inui.jpg", source:"https://segaplaza.jp/"},
{series:"toribe", name:"東京リベンジャーズ　九井一フィギュア", search:"ここのいはじめ", type:"", price:300, date:"1899-12-30", img:"images/toribe/kokonoi.jpg", source:"https://www.taito.co.jp/"},
{series:"kinniku", name:"キン肉マン サウナフィギュア-テリーマン-", search:"てりーまん", type:"", price:300, date:"1899-12-30", img:"images/kinniku/teri_sauna.jpg", source:"https://bsp-prize.jp/"},
{series:"kinniku", name:"キン肉マン サウナフィギュア-キン肉マン-", search:"きんにくまん", type:"", price:600, date:"1899-12-30", img:"images/kinniku/kin_sauna.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】　Vivitフィギュア アイ チアリーディングVer.", search:"あい", type:"vivi", price:500, date:"1899-12-30", img:"images/osinoko/ai_vivi.jpg", source:"http://www.fans.co.jp/"},
{series:"oba", name:"オーバーロード IFアルベドフィギュア-teacher style ver.-", search:"あるべど", type:"", price:500, date:"1899-12-30", img:"images/oba/aru_tea.jpg", source:"https://bsp-prize.jp/"},
{series:"deara", name:"デート・ア・ライブ GLITTER&GLAMOURS-KURUMI TOKISAKI-", search:"ときさきくるみ", type:"gli", price:400, date:"1899-12-30", img:"images/deara/kurumi_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"witti", name:"TVアニメ『ウィッチウォッチ』　浴衣フィギュア 若月ニコ", search:"わかつきにこ", type:"", price:300, date:"1899-12-30", img:"images/witti/niko_yukata.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"witti", name:"TVアニメ『ウィッチウォッチ』　浴衣フィギュア 宮尾音夢", search:"みやおねむ", type:"", price:300, date:"1899-12-30", img:"images/witti/nemu_yukata.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"sao", name:"ソードアート・オンライン BiCute Bunnies Figureーアスナー", search:"あすな", type:"bani", price:600, date:"1899-12-30", img:"images/sao/asuna_bani.jpg", source:"https://charahiroba.com/"},
{series:"100kano", name:"君のことが大大大大大好きな100人の彼女 -Relax time-花園羽香里", search:"はなぞのはかり", type:"relax", price:1000, date:"1899-12-30", img:"images/100kano/hana_relax.jpg", source:"https://bsp-prize.jp/"},
{series:"konosuba", name:"この素晴らしい世界に祝福を！３　Coreful フィギュア　ダクネス～水着ver.～", search:"だくねす", type:"core", price:900, date:"1899-12-30", img:"images/konosuba/daku_core_mizugi.jpg", source:"https://www.taito.co.jp/"},
{series:"spy", name:"SPY×FAMILY　Trio－Try－iT Figureーアーニャ・フォージャーー", search:"あーにゃふぉーじゃー", type:"trio", price:500, date:"1899-12-30", img:"images/spy/anya_trio.jpg", source:"https://charahiroba.com/"},
{series:"kimetu", name:"「鬼滅の刃」　FIGURIZMα　“甘露寺蜜璃”", search:"かんろじみつり", type:"fig", price:1300, date:"1899-12-30", img:"images/kimetu/kanrozi_fig.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 MAXIMATIC THE MITSURI KANROJI", search:"かんろじみつり", type:"ma", price:1700, date:"1899-12-30", img:"images/kimetu/kanrozi_ma.jpg", source:"https://bsp-prize.jp/"},
{series:"botti", name:"アニメ「ぼっち・ざ・ろっく！」 伊地知虹夏 フィギュア vol.2", search:"いじちにじか", type:"", price:600, date:"1899-12-30", img:"images/botti/nizika2.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】　Aqua Float Girls フィギュア　アイ", search:"あい", type:"aqua", price:900, date:"1899-12-30", img:"images/osinoko/ai_aqua.jpg", source:"https://www.taito.co.jp/"},
{series:"atorie", name:"アニメ『ライザのアトリエ ～常闇の女王と秘密の隠れ家～』　Coreful フィギュア　ライザ～水着ver.～", search:"らいざ", type:"core", price:600, date:"1899-12-30", img:"images/atorie/raiza_core_mizugi.jpg", source:"https://www.taito.co.jp/"},
{series:"sonota", name:"勇気爆発バーンブレイバーン Break time collection vol.1", search:"ゆうきばくはつばーんぶれいばーん", type:"bre", price:300, date:"1899-12-30", img:"images/sonota/ban_bre.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース フィグライフ! モンキー・D・ルフィ-ギア5-vol.4", search:"るふぃ　ニカ　にか", type:"figl", price:400, date:"1899-12-30", img:"images/wanpi/nika_figl4.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】 アイ-サインはB-フィギュア", search:"あい", type:"", price:600, date:"1899-12-30", img:"images/osinoko/ai_b.jpg", source:"https://bsp-prize.jp/"},
{series:"eva", name:"シン・エヴァンゲリオン劇場版Luminasta“真希波・マリ・イラストリアス”", search:"まきなみまりいらすとりあす", type:"lum", price:800, date:"1899-12-30", img:"images/eva/mari_lum.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"鬼滅の刃 ぬーどるストッパーフィギュア ―伊黒小芭内―", search:"いぐろおばない", type:"nusuto", price:4500, date:"1899-12-30", img:"images/kimetu/iguro_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"zyuzyutu", name:"呪術廻戦懐玉・玉折FIGURIZMα“五条悟”覚醒", search:"ごじょうさとる", type:"fig", price:1300, date:"1899-12-30", img:"images/zyuzyutu/gozyo_kakusei.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"鬼滅の刃　プレミアムちょこのせフィギュア“煉󠄁獄杏寿郎”", search:"れんごくきょうじゅろう", type:"tyoko", price:800, date:"1899-12-30", img:"images/kimetu/rengoku_tyoko_oni.jpg", source:"https://segaplaza.jp/"},
{series:"mazyotabi", name:"魔女の旅々　AMP＋ イレイナ フィギュア～魔女服ver.～", search:"いれいな", type:"amp", price:1000, date:"1899-12-30", img:"images/mazyotabi/amp.jpg", source:"https://www.taito.co.jp/"},
{series:"naruto", name:"NARUTO-ナルト- BANPRESTO FIGURE COLOSSEUM 造形忍界大戦 ロック・リー", search:"ろっくりー", type:"ninkai", price:2300, date:"1899-12-30", img:"images/naruto/ri_ninkai.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース THE出航-NAMI-", search:"なみ　ナミ", type:"syukko", price:500, date:"1899-12-30", img:"images/wanpi/nami_syukko.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～マイメロディ・クロミ～", search:"まいめろでぃ", type:"", price:500, date:"2026-05-27", img:"images/sanrio/maimero_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～マイメロディ・クロミ～", search:"くろみ", type:"", price:500, date:"2026-05-27", img:"images/sanrio/kuromi_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 鎮座獣 コイン怪獣カネゴン", search:"こいんかいじゅうかねごん", type:"tinza", price:500, date:"2026-05-27", img:"images/uru/kane_tinza.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 鎮座獣 コイン怪獣カネゴン", search:"こいんかいじゅうかねごん", type:"tinza", price:500, date:"2026-05-27", img:"images/uru/kane_tinza_b.jpg", source:"https://bsp-prize.jp/"},
{series:"monhan", name:"モンスターハンター 鎮座獣 アルシュベルド～夢から覚めて～", search:"あるしゅべると", type:"tinza", price:500, date:"2026-05-27", img:"images/monhan/arusyu_tinza.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"Trio-Try-iT Figureージジ(変身)ー", search:"じじ", type:"trio", price:500, date:"2026-05-27", img:"images/dandadan/zizi_trio.jpg", source:"https://charahiroba.com/"},
{series:"umamusume", name:"Trio-Try-iT Figure―ヒシミラクルー", search:"ひしみらくる", type:"trio", price:900, date:"2026-05-27", img:"images/umamusume/hisi_trio.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブ #hololive IF -ホロベイビーズ-宝鐘マリン", search:"ほうしょうまりん", type:"", price:500, date:"2026-05-26", img:"images/holo/marin_baby.jpg", source:"https://bsp-prize.jp/"},
{series:"holo", name:"ホロライブ #hololive IF -ホロベイビーズ-こぼ・かなえる", search:"", type:"", price:500, date:"2026-05-26", img:"images/holo/kobo_baby.jpg", source:"https://bsp-prize.jp/"},
{series:"king", name:"キングダム オギコフィギュア", search:"おぎこ", type:"", price:500, date:"2026-05-27", img:"images/king/ogiko.jpg", source:"https://bsp-prize.jp/"},
{series:"tomuzyeri", name:"トムとジェリー ビッグソフビフィギュア-Yummy Bread-", search:"じぇりー　たふぃー　ジェリー　タフィー", type:"", price:500, date:"2026-05-27", img:"images/tomuzyeri/zyeritafi.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"UNIVERSAL おおきなSOFVIMATES～おさるのジョージ～", search:"おさるのじょーじ", type:"sof", price:400, date:"2026-05-26", img:"images/sonota/zyozi_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"TVアニメ『ダンダダン』 フィグライフ!モモ", search:"もも", type:"figl", price:400, date:"2026-05-26", img:"images/dandadan/momo_figl.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"初音ミクシリーズ　Luminasta　“初音ミク 16th Anniversary”KEI Ver.", search:"はつねみく", type:"lum", price:700, date:"1899-12-30", img:"images/miku/16_key.jpg", source:"https://segaplaza.jp/"},
{series:"db", name:"ドラゴンボールZ MATCH MAKERS 魔人ブウ（VS超サイヤ人3孫悟空）", search:"まじんぶう", type:"mat", price:600, date:"1899-12-30", img:"images/db/bu_mat_goku.jpg", source:"https://bsp-prize.jp/"},
{series:"king", name:"キングダム Grandistaｰ桓騎ｰ", search:"かんき", type:"gra", price:500, date:"2026-05-27", img:"images/king/kanki_gra.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュアvol.3", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"1899-12-30", img:"images/kuresin/kosu_buri.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュアvol.3", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"1899-12-30", img:"images/kuresin/kosu_kan.jpg", source:"https://bsp-prize.jp/"},
{series:"konan", name:"名探偵コナン XrossLink フィギュア“江戸川コナン”", search:"えどがわこなん", type:"xros", price:400, date:"1899-12-30", img:"images/konan/konan_xros.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナン XrossLink フィギュア“怪盗キッド”", search:"かいとうきっど", type:"xros", price:700, date:"1899-12-30", img:"images/konan/kiddo_xros.jpg", source:"https://segaplaza.jp/"},
{series:"gorukamu", name:"TVアニメ『ゴールデンカムイ』XrossLinkフィギュア“白石由竹”", search:"しらいしよしたけ", type:"xros", price:300, date:"1899-12-30", img:"images/gorukamu/siraisi_xros.jpg", source:"https://segaplaza.jp/"},
];
