window.figures3 = [

{series:"pro", name:"プロジェクトセカイカラフルステージ！feat.初音ミク Desktop×DecorateCollections “天馬司”", search:"てんまつかさ", type:"ddc", price:1000, date:"2025-05-23", img:"images/pro/tukasa_ddc.jpg", source:"https://segaplaza.jp/"},
{series:"skzoo", name:"SKZOO BIRTHDAY CAKE コレクションvol.2", search:"じにれっと　Jiniret", type:"", price:600, date:"2026-02-17", img:"images/skzoo/jini.jpg", source:"https://bsp-prize.jp/"},
{series:"skzoo", name:"SKZOO BIRTHDAY CAKE コレクションvol.4", search:"PuppyM　ぱぴーえむ", type:"", price:600, date:"2026-03-24", img:"images/skzoo/papi.jpg", source:"https://bsp-prize.jp/"},
{series:"skzoo", name:"SKZOO BIRTHDAY CAKE コレクションvol.4", search:"FoxI.Ny　ふぉくしにー", type:"", price:600, date:"2026-03-24", img:"images/skzoo/fox.jpg", source:"https://bsp-prize.jp/"},
{series:"skzoo", name:"SKZOO BIRTHDAY CAKE コレクションvol.3", search:"ぼっかり　BbokAri", type:"", price:600, date:"2026-03-24", img:"images/skzoo/bbo.jpg", source:"https://bsp-prize.jp/"},
{series:"skzoo", name:"SKZOO BIRTHDAY CAKE コレクションvol.3", search:"HAN QUOKKA　はんくわっか", type:"", price:600, date:"2026-03-24", img:"images/skzoo/han.jpg", source:"https://bsp-prize.jp/"},
{series:"hora", name:"DEATH STRANDING 2: ON THE BEACH モニタートップフィギュア-サム-", search:"さむ", type:"moni", price:500, date:"2026-06-23", img:"images/hora/samu_moni.jpg", source:"https://bsp-prize.jp/"},
{series:"haikyu", name:"ハイキュー!! すやすやルームライト-月島 蛍-", search:"つきしまけい", type:"", price:600, date:"2026-04-09", img:"images/haikyu/tuki_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"TVアニメ『ダンダダン』 VIBRATION STARS-オカルン(変身)-", search:"おかるん", type:"vib", price:400, date:"2026-06-23", img:"images/dandadan/oka_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"TVアニメ『ダンダダン』 VIBRATION STARS-ジジ(変身)-", search:"じじ", type:"vib", price:400, date:"2026-06-23", img:"images/dandadan/zizi_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"gundam", name:"『機動戦士Gundam GQuuuuuuX』 アマテ・ユズリハ（マチュ）＆ハロ フィギュア エンディング ver.", search:"あまてゆずりは　まちゅ　はろ", type:"", price:500, date:"2026-06-23", img:"images/gundam/matyu_ed.jpg", source:"https://bsp-prize.jp/"},
{series:"gundam", name:"『機動戦士Gundam GQuuuuuuX』 ニャアン＆コンチ フィギュア エンディング ver.", search:"にゃあん　こんち", type:"", price:500, date:"2026-06-23", img:"images/gundam/nya_ed.jpg", source:"https://bsp-prize.jp/"},
{series:"zigoku", name:"地獄楽 VIBRATION STARS-画眉丸＆山田浅ェ門 佐切-", search:"がびまる", type:"vib", price:500, date:"2026-06-23", img:"images/zigoku/gabi_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"zigoku", name:"地獄楽 VIBRATION STARS-画眉丸＆山田浅ェ門 佐切-", search:"やまだあさぇもんさぎり", type:"vib", price:500, date:"2026-06-23", img:"images/zigoku/sagiri_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"yurukyan", name:"ゆるキャン△ SEASON３　Trio－Try－iT Figureー各務原なでしこー", search:"かがみはらなでしこ", type:"trio", price:600, date:"2026-06-23", img:"images/yurukyan/nade_trio.jpg", source:"https://charahiroba.com/"},
{series:"sonota", name:"どこでもいっしょ モニタートップフィギュア～トロ・クロ～", search:"とろ", type:"moni", price:400, date:"2026-06-23", img:"images/sonota/toro_moni.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"どこでもいっしょ モニタートップフィギュア～トロ・クロ～", search:"くろ", type:"moni", price:400, date:"2026-06-23", img:"images/sonota/kuro_moni.jpg", source:"https://bsp-prize.jp/"},
{series:"eva", name:"新世紀エヴァンゲリオンハイプレミアムフィギュア “アスカ”制服Ver.", search:"あすか", type:"hi", price:800, date:"2025-10-17", img:"images/eva/asuka_hi.jpg", source:"https://segaplaza.jp/"},
{series:"kisekoi", name:"TVアニメ「その着せ替え人形は恋をする」 ESPRESTO-Detailed Elegance-喜多川海夢 ブラックロベリアver.", search:"きたがわまりん　ぶらっくろべりあ", type:"esp", price:800, date:"2025-05-27", img:"images/kisekoi/burarobe_esp.jpg", source:"https://bsp-prize.jp/"},
{series:"holo", name:"ホロライブプロダクション　ひっかけフィギュア Vol.3　戌神ころね", search:"いぬがみころね", type:"hikkake", price:300, date:"2025-06-27", img:"images/holo/hikkake_korone.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブプロダクション　ひっかけフィギュア Vol.3　ロボ子さん", search:"ろぼこさん", type:"hikkake", price:300, date:"2025-06-27", img:"images/holo/hikkake_roboko.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブプロダクション　ひっかけフィギュア Vol.3　猫又おかゆ", search:"ねこまたおかゆ", type:"hikkake", price:300, date:"2025-06-27", img:"images/holo/hikkake_okayu.jpg", source:"https://charahiroba.com/"},
{series:"umamusume", name:"ウマ娘 プリティーダービー イクノディクタス フィギュア", search:"いくのでぃくたす", type:"", price:400, date:"2023-03-09", img:"images/umamusume/ikuno.jpg", source:"https://bsp-prize.jp/"},
{series:"oba", name:"オーバーロード　Coreful フィギュア　アルベド～メイドver.～", search:"あるべど", type:"core", price:500, date:"2025-05-17", img:"images/oba/aru_core_meido.jpg", source:"https://www.taito.co.jp/"},
{series:"oba", name:"オーバーロード　Coreful フィギュア　アルベド～メイドver.～Renewal", search:"あるべど", type:"core", price:500, date:"2025-05-17", img:"images/oba/aru_core_meido_re.jpg", source:"https://www.taito.co.jp/"},
{series:"rikorisu", name:"リコリス・リコイルLuminasta“井ノ上たきな - チャイナStyle”", search:"いのうえたきな", type:"lum", price:400, date:"2025-03-21", img:"images/rikorisu/takina_china_lum.jpg", source:"https://segaplaza.jp/"},
{series:"rikorisu", name:"リコリス・リコイルLuminasta“錦木千束 - チャイナStyle”", search:"にしきぎちさと", type:"lum", price:500, date:"2025-03-14", img:"images/rikorisu/tisato_china_lum.jpg", source:"https://segaplaza.jp/"},
{series:"yaiba", name:"真･侍伝YAIBA 鉄刃＆カゲトラフィギュア-ガオ～ッ♬-", search:"やいば", type:"", price:800, date:"2025-09-25", img:"images/yaiba/yaikage.jpg", source:"https://bsp-prize.jp/"},
{series:"yaiba", name:"真･侍伝YAIBA 鉄刃＆カゲトラフィギュア-ガオ～ッ♬-", search:"かげとら", type:"", price:800, date:"2025-09-25", img:"images/yaiba/kageyai.jpg", source:"https://bsp-prize.jp/"},
{series:"zyozyo", name:"スティール・ボール・ラン ジョジョの奇妙な冒険 Mometria ジョニィ・ジョースター", search:"じょにぃじょーすたー", type:"", price:1200, date:"2026-06-25", img:"images/zyozyo/zyoni.jpg", source:"https://bsp-prize.jp/"},
{series:"zyozyo", name:"スティール・ボール・ラン ジョジョの奇妙な冒険 Mometria ジャイロ・ツェペリ", search:"じゃいろつぇぺり", type:"", price:1200, date:"2026-06-25", img:"images/zyozyo/zyairo.jpg", source:"https://bsp-prize.jp/"},
{series:"dr", name:"Dr.STONE スイカ(成長後)フィギュア", search:"すいか", type:"", price:1300, date:"2026-06-23", img:"images/dr/suika.jpg", source:"https://bsp-prize.jp/"},
{series:"rakisuta", name:"Trio-Try-iT Figure ー 柊つかさ ー", search:"ひいらぎつかさ", type:"trio", price:1100, date:"2026-06-24", img:"images/rakisuta/tukasa_trio.jpg", source:"https://charahiroba.com/"},
{series:"oba", name:"オーバーロード　武 モモン", search:"ももん", type:"", price:1200, date:"2026-06-25", img:"images/oba/momon.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"oba", name:"オーバーロード　武 コキュートス", search:"こきゅーとす", type:"", price:1100, date:"2026-06-25", img:"images/oba/kokyu.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"miku", name:"初音ミク×シナモロールちょこのせプレミアムフィギュア‐初音ミク×シナモロール‐もふっとVer.", search:"はつねみく　しなもろーる", type:"tyoko", price:1200, date:"2026-06-26", img:"images/miku/sinamo_mofu.jpg", source:"https://segaplaza.jp/"},
{series:"wanpi", name:"ワンピース MAXIMATICPLUS MONKEY.D.LUFFY Ⅱ", search:"るふぃ　ルフィ", type:"ma", price:1100, date:"2026-06-25", img:"images/wanpi/rufi_ma2.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦死滅回游FIGURIZMα“乙骨憂太”", search:"おっこつゆうた", type:"fig", price:1100, date:"2026-06-26", img:"images/zyuzyutu/otu_fig.jpg", source:"https://segaplaza.jp/"},
{series:"fate", name:"TVアニメ『Fate/strange Fake』Whispers of Dawn　アーチャー", search:"あーちゃー", type:"", price:1100, date:"2026-06-25", img:"images/fate/atya.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"fate", name:"TVアニメ『Fate/strange Fake』Whispers of Dawn　ランサー", search:"らんさー", type:"", price:1000, date:"2026-06-25", img:"images/fate/ransa.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"roze", name:"Trio-Try-iT Figure ー真紅ー", search:"しんく", type:"trio", price:1000, date:"2026-06-27", img:"images/roze/sinku_trio.jpg", source:"https://charahiroba.com/"},
{series:"sibo", name:"死亡遊戯で飯を食う。　BiCute Bunnies Figureー幽鬼ー", search:"ゆうき", type:"bani", price:1000, date:"2026-06-27", img:"images/sibo/yuki_bani.jpg", source:"https://charahiroba.com/"},
{series:"hant", name:"HUNTER×HUNTER Exc∞d Creative Figureーヒソカー", search:"ひそか", type:"ex", price:900, date:"2026-06-25", img:"images/hant/hisoka_ex.jpg", source:"https://charahiroba.com/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 VIBRATION STARS-猗窩座・狛治-", search:"あかざ", type:"vib", price:1000, date:"2026-06-25", img:"images/kimetu/akaza_hakuzi_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 VIBRATION STARS-猗窩座・狛治-", search:"はくじ", type:"vib", price:1000, date:"2026-06-25", img:"images/kimetu/hakuzi_akaza_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 豪塊 キングジョー", search:"きんぐじょー", type:"", price:1100, date:"2026-06-25", img:"images/uru/kingzyo.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 豪塊 キングジョー", search:"きんぐじょー", type:"", price:1100, date:"2026-06-25", img:"images/uru/kingzyo_b.jpg", source:"https://bsp-prize.jp/"},
{series:"madomagi", name:"劇場版 魔法少女まどか☆マギカ〈ワルプルギスの廻天〉 佐倉杏子 フィギュア", search:"さくらきょうこ", type:"", price:1000, date:"2026-06-23", img:"images/madomagi/kyoko_kaiten.jpg", source:"https://bsp-prize.jp/"},
{series:"naruto", name:"NARUTO-ナルト- 疾風伝 Memorable Saga Special-うちはサスケ-", search:"うちはさすけ", type:"memo", price:1100, date:"2026-06-23", img:"images/naruto/sasuke3_memo.jpg", source:"https://bsp-prize.jp/"},
{series:"kon", name:"けいおん！Yumemirize‐平沢唯‐", search:"ひらさわゆい", type:"yume", price:1000, date:"2026-06-26", img:"images/kon/yui_yume.jpg", source:"https://segaplaza.jp/"},
{series:"kon", name:"けいおん！Yumemirize‐中野梓‐", search:"なかのあずさ", type:"yume", price:1000, date:"2026-06-26", img:"images/kon/azusa_yume.jpg", source:"https://segaplaza.jp/"},
{series:"miku", name:"初音ミク　ぬーどるストッパーフィギュア 初音ミクJAPAN LIVE TOUR 2025 ～BLOOMING～", search:"はつねみく　ぶるーみんぐ　ブルーミング　ライブツアー　らいぶつあー", type:"nusuto", price:900, date:"2026-06-27", img:"images/miku/live_2025.jpg", source:"https://charahiroba.com/"},
{series:"furi-ren", name:"葬送のフリーレンYumemirize“フリーレン”～ルームウェア～", search:"ふりーれん", type:"yume", price:900, date:"2026-06-26", img:"images/furi-ren/furi_yume_rumu.jpg", source:"https://segaplaza.jp/"},
{series:"umamusume", name:"ウマ娘プリティーダービーXStellar“サトノダイヤモンド”おすわりVer.", search:"さとのだいやもんど", type:"xs", price:900, date:"2026-06-26", img:"images/umamusume/satoda_xs.jpg", source:"https://segaplaza.jp/"},
{series:"botti", name:"アニメ「ぼっち・ざ・ろっく！」　ふぃぐきゅーぶ 後藤ひとり", search:"ごとうひとり　ぼっち", type:"figc", price:1100, date:"2026-06-25", img:"images/botti/botti_figc.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"botti", name:"アニメ「ぼっち・ざ・ろっく！」　ふぃぐきゅーぶ 山田リョウ", search:"やまだりょう", type:"figc", price:1100, date:"2026-06-25", img:"images/botti/ryo_figc.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"botti", name:"アニメ「ぼっち・ざ・ろっく！」　ふぃぐきゅーぶ 伊地知虹夏", search:"いじちにじか", type:"figc", price:900, date:"2026-06-25", img:"images/botti/nizika_figc.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"botti", name:"アニメ「ぼっち・ざ・ろっく！」　ふぃぐきゅーぶ 喜多郁代", search:"きたいくよ", type:"figc", price:900, date:"2026-06-25", img:"images/botti/ikuyo_figc.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"kisekoi", name:"TVアニメ「その着せ替え人形は恋をする」Season 2 GLITTER&GLAMOURS-喜多川海夢 十六夜ありさver.-", search:"きたがわまりん　いざよいありさ", type:"gli", price:1000, date:"2026-06-25", img:"images/kisekoi/arisa_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"furi-ren", name:"葬送のフリーレン EFFECTREME-FERN-", search:"ふぇるん　フェルン", type:"eff", price:900, date:"2026-06-25", img:"images/furi-ren/fe_eff.jpg", source:"https://bsp-prize.jp/"},
{series:"furi-ren", name:"葬送のフリーレン EFFECTREME-FRIEREN-", search:"ふりーれん　フリーレン", type:"eff", price:1100, date:"2026-06-25", img:"images/furi-ren/furi_eff.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦 MAXIMATIC MEGUMI FUSHIGURO-死滅回游-", search:"ふしぐろめぐみ　伏黒恵", type:"ma", price:900, date:"2026-06-25", img:"images/zyuzyutu/fusi_ma_simetu.jpg", source:"https://bsp-prize.jp/"},
{series:"soniko", name:"すーぱーそに子　BiCute Bunnies Figureー逆バニーー", search:"すーぱーそにこ", type:"bani", price:900, date:"2026-06-25", img:"images/soniko/gyakubani.jpg", source:"https://charahiroba.com/"},
{series:"oba", name:"オーバーロード　Masquerade アルベド チアガールVer.", search:"あるべど", type:"", price:800, date:"2026-06-25", img:"images/oba/aru_tia_konami.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"yusyakei", name:"Trio-Try-iT Figure ーテオリッター", search:"ておりった", type:"trio", price:800, date:"2026-06-24", img:"images/yusyakei/teo_trio.jpg", source:"https://charahiroba.com/"},
{series:"wanpi", name:"ワンピース メガワールドコレクタブルフィギュア-鉄の巨人-", search:"てつのきょじん", type:"wcf", price:1000, date:"2026-06-23", img:"images/wanpi/kyozin_wcf.jpg", source:"https://bsp-prize.jp/"},
{series:"marizzi", name:"マリッジトキシン GLITTER&GLAMOURS-MEI KINOSAKI-", search:"きのさきめい　城崎メイ", type:"gli", price:900, date:"2026-06-23", img:"images/marizzi/mei_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"keroro", name:"ケロロ軍曹 GLITTER&GLAMOURS～モア～", search:"もあ", type:"gli", price:1000, date:"2026-06-23", img:"images/keroro/moa_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"gundam", name:"『機動戦士ガンダム』 限械突破 RX-78-2 ガンダム", search:"がんだむ", type:"", price:800, date:"2026-06-23", img:"images/gundam/gun_genkai.jpg", source:"https://bsp-prize.jp/"},
{series:"hiro", name:"僕のヒーローアカデミア GLITTER&GLAMOURS-HIMIKO TOGA-Ⅱ", search:"トガヒミコ　とがひみこ", type:"gli", price:600, date:"2026-06-23", img:"images/hiro/toga02_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"tora", name:"To LOVEる-とらぶる-ダークネス　Desktop Cute フィギュア　ナナ～チャイナドレスver.～", search:"なな", type:"desk", price:800, date:"2026-06-27", img:"images/tora/nana_desk_rumu.jpg", source:"https://www.taito.co.jp/"},
{series:"furi-ren", name:"葬送のフリーレンYumemirize“ユーベル”～ルームウェア～", search:"ゆーべる", type:"yume", price:800, date:"2026-06-26", img:"images/furi-ren/yube_yume.jpg", source:"https://segaplaza.jp/"},
{series:"kanokari", name:"彼女、お借りしますYumemirize“水原千鶴”", search:"みずはらちづる", type:"yume", price:800, date:"2026-06-26", img:"images/kanokari/mizuhara_yume.jpg", source:"https://segaplaza.jp/"},
{series:"rupan", name:"LUPIN THE ⅢRD 次元大介 フィギュア", search:"じげんだいすけ", type:"", price:700, date:"2026-06-25", img:"images/rupan/zigen.jpg", source:"https://bsp-prize.jp/"},
{series:"mazyotabi", name:"Trio-Try-iT Figureーイレイナ・ワンピースver.ー", search:"いれいな", type:"trio", price:800, date:"2026-06-23", img:"images/mazyotabi/wanpi_trio.jpg", source:"https://charahiroba.com/"},
{series:"osarabu", name:"ぬーどるストッパーフィギュア ー 水萌汐 ー", search:"みなもしお", type:"nusuto", price:800, date:"2026-06-25", img:"images/osarabu/sio_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"akuse", name:"ぬーどるストッパーフィギュア―黒雪姫―", search:"くろゆきひめ", type:"nusuto", price:800, date:"2026-06-24", img:"images/akuse/kuro_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"cityhu", name:"ぬーどるストッパーフィギュアー冴羽獠ー", search:"さえばりょう", type:"nusuto", price:800, date:"2026-06-24", img:"images/cityhu/ryo_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"hokuto", name:"北斗の拳 -FIST OF THE NORTH STAR-Grandista-REI-", search:"れい　レイ", type:"gra", price:700, date:"2026-06-23", img:"images/hokuto/rei_gra.jpg", source:"https://bsp-prize.jp/"},
{series:"nukitasi", name:"Trio-Try-iT Figure ー 片桐奈々瀬 ー", search:"かたぎりななせ", type:"trio", price:700, date:"2026-06-24", img:"images/nukitasi/nanase_trio.jpg", source:"https://charahiroba.com/"},
{series:"nukitasi", name:"Trio-Try-iT Figure ー 畔美岬 ー", search:"ほとりみさき", type:"trio", price:700, date:"2026-06-24", img:"images/nukitasi/hotori_trio.jpg", source:"https://charahiroba.com/"},
{series:"ramune", name:"Trio-Try-iT Figure ー柊 夕湖ー", search:"ひいらぎゆうこ", type:"trio", price:700, date:"2026-06-24", img:"images/ramune/hira_trio.jpg", source:"https://charahiroba.com/"},
{series:"rezero", name:"Re:ゼロから始める異世界生活 MeloDoll Figure―ラム・ナイトドレス―", search:"らむ", type:"melo", price:700, date:"2026-06-27", img:"images/rezero/ramu_mero.jpg", source:"https://charahiroba.com/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 02", search:"ベジータ　べじーた", type:"supi", price:600, date:"2026-06-23", img:"images/db/bezi_supi_a.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 02", search:"ベジータ　べじーた", type:"supi", price:600, date:"2026-06-23", img:"images/db/bezi_supi_b.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 02", search:"ベジータ　べじーた", type:"supi", price:600, date:"2026-06-23", img:"images/db/bezi_supi_c.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 02", search:"ベジータ　べじーた", type:"supi", price:600, date:"2026-06-23", img:"images/db/bezi_supi_d.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"Minions おおきなSOFVIMATES～ボブ～", search:"ぼぶ", type:"sof", price:700, date:"2026-06-23", img:"images/sonota/bobu_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"gundam", name:"『機動戦士ガンダムＵＣ』 胸像センサーライト-ユニコーンガンダム（デストロイモード 最終決戦仕様）-", search:"ゆにこーんがんだむ", type:"", price:600, date:"2026-06-23", img:"images/gundam/yuni_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"holo", name:"ホロライブ #hololive IF -Relax time-雪花ラミィ", search:"ゆきはならみぃ", type:"relax", price:600, date:"2026-06-25", img:"images/holo/rami_if_relax.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～昼下がりのおままごと～マサオくんと", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"2026-06-23", img:"images/kuresin/sinmasa_omama.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～昼下がりのおままごと～マサオくんと", search:"マサオくん　まさおくん", type:"", price:600, date:"2026-06-23", img:"images/kuresin/masasin_omama.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～昼下がりのおままごと～ボーちゃんと", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"2026-06-23", img:"images/kuresin/sinbo_omama.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～昼下がりのおままごと～ボーちゃんと", search:"ボーちゃん　ぼーちゃん", type:"", price:600, date:"2026-06-23", img:"images/kuresin/bosin_omama.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"初音ミクシリーズ Luminasta “初音ミク-ビターパティシエ”", search:"はつねみく　びたーぱてぃしえ", type:"lum", price:1000, date:"2023-01-27", img:"images/miku/bita_lum.jpg", source:"https://segaplaza.jp/"},
{series:"dorakue", name:"ドラゴンクエスト　AM　ピンチハンガー　メタルホイミン", search:"めたるほいみん", type:"", price:300, date:"2026-06-19", img:"images/dorakue/metaho.jpg", source:"https://www.taito.co.jp/"},
{series:"bururo", name:"TVアニメ『ブルーロック』 御影玲王 フィギュア", search:"みかげれお", type:"", price:600, date:"2023-02-07", img:"images/bururo/reo1.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦Luminasta“脹相”", search:"ちょうそう", type:"lum", price:1800, date:"2025-02-07", img:"images/zyuzyutu/tyou_lum.jpg", source:"https://segaplaza.jp/"},
{series:"nintama", name:"劇場版 忍たま乱太郎 ドクタケ忍者隊最強の軍師 ぬーどるストッパーフィギュアー天鬼ー", search:"てんき", type:"nusuto", price:300, date:"2025-08-08", img:"images/nintama/tenki_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"gundam", name:"機動戦士Gundam GQuuuuuuX 限械突破 GFreD(ジフレド）", search:"じふれど", type:"", price:400, date:"2025-07-17", img:"images/gundam/zifu.jpg", source:"https://bsp-prize.jp/"},
{series:"mar", name:"DCACT/CUTプレミアムフィギュア“ジョーカー”", search:"じょーかー", type:"act", price:600, date:"2024-10-25", img:"images/mar/zyoka_act.jpg", source:"https://segaplaza.jp/"},
{series:"pro", name:"プロジェクトセカイカラフルステージ！feat.初音ミク Desktop×DecorateCollections “小豆沢こはね”", search:"あずさわこはね", type:"ddc", price:600, date:"2025-04-04", img:"images/pro/kohane_ddc.jpg", source:"https://segaplaza.jp/"},
{series:"rosidere", name:"TVアニメ『時々ボソッとロシア語でデレる隣のアーリャさん』Luminasta“アーリャ”－水着－", search:"あーりゃ", type:"lum", price:400, date:"2025-02-14", img:"images/rosidere/arya_mizu_lum.jpg", source:"https://segaplaza.jp/"},
{series:"rezero", name:"王選候補者と騎士フィギュア ーフェルト陣営ー　フェルト", search:"ふぇると　フェルト", type:"", price:1400, date:"2026-06-06", img:"images/rezero/feru_gigo.jpg", source:"https://charahiroba.com/"},
{series:"rezero", name:"王選候補者と騎士フィギュア ーフェルト陣営ー　ラインハルト", search:"らいんはると　ラインハルト", type:"", price:1800, date:"2026-06-06", img:"images/rezero/rain_gigo.jpg", source:"https://charahiroba.com/"},
{series:"wanpi", name:"ワンピース BATTLE RECORD COLLECTION-SHANKS-SPECIAL ver.", search:"シャンクス　しゃんくす", type:"bato", price:600, date:"2025-12-18", img:"images/wanpi/syan_bato.jpg", source:"https://bsp-prize.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」XrossLinkフィギュア“幼少期の冨岡義勇”", search:"とみおかぎゆう", type:"xros", price:5000, date:"1899-12-30", img:"images/kimetu/you_giyu_xros.jpg", source:"https://segaplaza.jp/"},
{series:"yahari", name:"やはり俺の青春ラブコメはまちがっている。完XStellar“由比ヶ浜結衣”～放課後通り雨～", search:"ゆいがはまゆい", type:"xs", price:800, date:"2026-06-19", img:"images/yahari/yui_xs.jpg", source:"https://segaplaza.jp/"},
{series:"umamusume", name:"ウマ娘プリティーダービーXStellar“アストンマーチャン”おすわりVer.", search:"あすとんまーちゃん", type:"xs", price:900, date:"2026-06-19", img:"images/umamusume/asu_xs_osu.jpg", source:"https://segaplaza.jp/"},
{series:"youzitu", name:"TVアニメ「ようこそ実力至上主義の教室へ」ちょこのせプレミアムフィギュア‐天沢一夏‐", search:"あまさわいちか", type:"tyoko", price:900, date:"2026-06-19", img:"images/youzitu/itika_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"youzitu", name:"TVアニメ「ようこそ実力至上主義の教室へ」ちょこのせプレミアムフィギュア‐軽井沢恵‐", search:"かるいざわけい", type:"tyoko", price:1000, date:"2026-06-26", img:"images/youzitu/kei_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"rosidere", name:"時々ボソッとロシア語でデレる隣のアーリャさん One-Seventh Caratフィギュア アーリャ バニーVer. RED", search:"あーりゃ", type:"one", price:700, date:"2026-06-19", img:"images/rosidere/one_red.jpg", source:"http://www.fans.co.jp/"},
{series:"bakatesu", name:"バカとテストと召喚獣 BiCute Bunnies Figure―木下秀吉―", search:"きのしたひでよし", type:"bani", price:800, date:"2026-06-19", img:"images/bakatesu/hide_bani.jpg", source:"https://charahiroba.com/"},
{series:"sunobo", name:"スノウボールアース ソフビフィギュア～ユキオ～", search:"ゆきお", type:"sof", price:800, date:"2026-06-18", img:"images/sunobo/yukio_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～ぶりぶりざえもんしんちゃんとワニ山さんしんちゃん～", search:"野原しんのすけ　のはらしんのすけ　わにやま", type:"", price:600, date:"2026-06-09", img:"images/kuresin/kosu_wani.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～ぶりぶりざえもんしんちゃんとワニ山さんしんちゃん～", search:"野原しんのすけ　のはらしんのすけ　", type:"", price:600, date:"2026-06-09", img:"images/kuresin/kosu_buriburi.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦 KING OF ARTIST SUGURU GETO-懐玉・玉折-Ⅱ", search:"げとうすぐる　夏油傑", type:"koa", price:800, date:"1899-12-30", img:"images/zyuzyutu/geto2_koa.jpg", source:"https://bsp-prize.jp/"},
{series:"disny", name:"トイ・ストーリー　ぬーどるストッパーフィギュアーウッディー", search:"うっでぃ", type:"nusuto", price:700, date:"2026-06-18", img:"images/disny/ude_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"wanpi", name:"ワンピース ワールドコレクタブルフィギュア SPECIAL サボVS五老星＆イム様", search:"さぼ　いむ", type:"wcf", price:500, date:"1899-12-30", img:"images/wanpi/sabo_imu_wcf.jpg", source:"https://bsp-prize.jp/"},
{series:"dorakue", name:"ドラゴンクエスト　AM　とうぞくのカギで開く！宝箱", search:"たからばこ", type:"", price:600, date:"2026-05-30", img:"images/dorakue/takara.jpg", source:"https://www.taito.co.jp/"},
{series:"buri", name:"BLEACH GLITTER&GLAMOURS-NEMU KUROTSUCHI-", search:"涅ネム　くろつちねむ", type:"gli", price:1100, date:"2026-06-18", img:"images/buri/nemu_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"madomagi", name:"劇場版 魔法少女まどか☆マギカ〈ワルプルギスの廻天〉 暁美ほむら フィギュア", search:"あけみほむら", type:"", price:1000, date:"2026-06-18", img:"images/madomagi/homura_kaiten.jpg", source:"https://bsp-prize.jp/"},
{series:"madomagi", name:"劇場版 魔法少女まどか☆マギカ〈ワルプルギスの廻天〉 美樹さやか フィギュア", search:"みきさやか", type:"", price:800, date:"2026-06-18", img:"images/madomagi/sayaka_kaiten.jpg", source:"https://bsp-prize.jp/"},
{series:"madomagi", name:"劇場版 魔法少女まどか☆マギカ〈ワルプルギスの廻天〉 巴マミ フィギュア", search:"ともえまみ", type:"", price:900, date:"2026-06-18", img:"images/madomagi/mami_kaiten.jpg", source:"https://bsp-prize.jp/"},
{series:"rakisuta", name:"Trio-Try-iT Figureー柊かがみー", search:"ひいらぎかがみ", type:"trio", price:1000, date:"2026-06-17", img:"images/rakisuta/kagami_trio.jpg", source:"https://charahiroba.com/"},
{series:"naruto", name:"NARUTO-ナルト- 疾風伝 Grandista-HATAKE KAKASHI-Ⅱ", search:"はたけカカシ　はたけかかし", type:"gra", price:1000, date:"2026-06-18", img:"images/naruto/kakasi2_gra.jpg", source:"https://bsp-prize.jp/"},
{series:"guru", name:"東京喰種 Grandista-KANEKI KEN Ⅱ-", search:"金木研　かねきけん", type:"gra", price:700, date:"2026-06-18", img:"images/guru/kaneki2_gra.jpg", source:"https://bsp-prize.jp/"},
{series:"kinniku", name:"『キン肉マン』完璧超人始祖編 リアルフィギュア-グリムリパー-", search:"ぐりむりぱー", type:"", price:400, date:"2026-06-11", img:"images/kinniku/gurimu.jpg", source:"https://bsp-prize.jp/"},
{series:"naruto", name:"NARUTO-ナルト- 疾風伝 VIBRATION STARS-HIDAN-", search:"飛弾　ひだん", type:"vib", price:1800, date:"1899-12-30", img:"images/naruto/hidan_vib_b.jpg", source:"https://bsp-prize.jp/"},
{series:"gintama", name:"銀魂 おおきなSOFVIMATES～ギンザベス～", search:"ぎんざべす", type:"sof", price:1000, date:"2026-06-16", img:"images/gintama/ginza_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦 Figuno-YUJI ITADORI・MEGUMI FUSHIGURO-", search:"虎杖悠仁　いたどりゆうじ", type:"figu", price:500, date:"2026-06-16", img:"images/zyuzyutu/ita_figu_a.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦 Figuno-YUJI ITADORI・MEGUMI FUSHIGURO-", search:"虎杖悠仁　いたどりゆうじ", type:"figu", price:500, date:"2026-06-16", img:"images/zyuzyutu/ita_figu_b.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦 Figuno-YUJI ITADORI・MEGUMI FUSHIGURO-", search:"伏黒恵　ふしぐろめぐみ", type:"figu", price:500, date:"2026-06-16", img:"images/zyuzyutu/fusi_figu_a.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦 Figuno-YUJI ITADORI・MEGUMI FUSHIGURO-", search:"伏黒恵　ふしぐろめぐみ", type:"figu", price:500, date:"2026-06-16", img:"images/zyuzyutu/fusi_figu_b.jpg", source:"https://bsp-prize.jp/"},
{series:"hiro", name:"僕のヒーローアカデミア GLITTER&GLAMOURS-NEJIRE HADO-Ⅱ", search:"波動ねじれ　はどうねじれ", type:"gli", price:500, date:"2026-06-16", img:"images/hiro/nezire_gli_a.jpg", source:"https://bsp-prize.jp/"},
{series:"hiro", name:"僕のヒーローアカデミア GLITTER&GLAMOURS-NEJIRE HADO-Ⅱ", search:"波動ねじれ　はどうねじれ", type:"gli", price:500, date:"2026-06-16", img:"images/hiro/nezire_gli_b.jpg", source:"https://bsp-prize.jp/"},
{series:"pansuto", name:"New PANTY & STOCKING with GARTERBELT モニタートップフィギュア～Panty＆Stocking～", search:"パンティ　ぱんてぃ", type:"moni", price:1200, date:"2026-06-16", img:"images/pansuto/panty_moni.jpg", source:"https://bsp-prize.jp/"},
{series:"pansuto", name:"New PANTY & STOCKING with GARTERBELT モニタートップフィギュア～Panty＆Stocking～", search:"ストッキング　すとっきんぐ", type:"moni", price:1200, date:"2026-06-16", img:"images/pansuto/suto_moni.jpg", source:"https://bsp-prize.jp/"},
{series:"spy", name:"TVアニメ「SPY×FAMILY」Luminasta（アーニャ・フォージャー）なつやすみ", search:"あーにゃふぉーじゃー", type:"lum", price:1000, date:"1899-12-30", img:"images/spy/ukiwa_lum.jpg", source:"https://segaplaza.jp/"},
{series:"sakura", name:"カードキャプターさくら クリアカード編 フィギュア～木之本桜～", search:"きのもとさくら", type:"", price:1100, date:"2026-06-16", img:"images/sakura/kuria_sakura.jpg", source:"https://bsp-prize.jp/"},
{series:"kusuri", name:"薬屋のひとりごと 猫猫 フィギュア～月精～", search:"まおまお　げっせい", type:"", price:900, date:"2026-06-16", img:"images/kusuri/gessei.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース 戦光絶景-MONKEY.D.LUFFY-", search:"るふぃ　ルフィ　ニカ　にか", type:"senko", price:800, date:"2026-06-16", img:"images/wanpi/rufiboni_senko.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース 戦光絶景-JEWELRY.BONNEY-", search:"ジュエリーボニー　じゅえりーぼにー", type:"senko", price:800, date:"2026-06-16", img:"images/wanpi/bonirufi_senko.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボールZ MATCH MAKERS 孫悟空（VSベジータ)", search:"そんごくう", type:"mat", price:800, date:"2026-06-16", img:"images/db/gokubezi_mat.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボールZ MATCH MAKERS ベジータ（VS孫悟空)", search:"べじーた", type:"mat", price:900, date:"2026-06-16", img:"images/db/bezigoku_mat.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ フィギュア シナモロール ～コルネと一緒～", search:"しなもろーる　こるね", type:"sof", price:500, date:"2026-06-09", img:"images/sanrio/sinamo_korune.jpg", source:"https://bsp-prize.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“怪盗キッド”", search:"かいとうきっど", type:"peti", price:400, date:"2026-06-12", img:"images/konan/kiddo_peti.jpg", source:"https://segaplaza.jp/"},
{series:"miku", name:"ぬーどるストッパーフィギュアーエンプレス[ブラックロックシューター]ー", search:"ぶらっくろっくしゅーたー", type:"nusuto", price:800, date:"1899-12-30", img:"images/miku/bura_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"miku", name:"ブラック★★ロックシューター DAWN FALL　Coreful フィギュア　エンプレス【ブラックロックシューター】覚醒ver.", search:"ぶらっくろっくしゅーたー", type:"core", price:1100, date:"1899-12-30", img:"images/miku/bura_core.jpg", source:"https://www.taito.co.jp/"},
{series:"hiro", name:"僕のヒーローアカデミア THE AMAZING HEROES vol.16", search:"るみりおん　ルミリオン", type:"ame", price:600, date:"1899-12-30", img:"images/hiro/ame_16_rumio.jpg", source:"https://bsp-prize.jp/"},
{series:"hiro", name:"僕のヒーローアカデミア THE AMAZING HEROES vol.16", search:"波動ねじれ　はどうねじれ", type:"ame", price:600, date:"1899-12-30", img:"images/hiro/ame_16_hado.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"桜ミク　Coreful フィギュア　～描き下ろし和風喫茶ver.～（タイクレ限定）", search:"さくらみく　わふうきっさ", type:"core", price:1500, date:"1899-12-30", img:"images/miku/wafu_taikure.jpg", source:"https://www.taito.co.jp/"},
{series:"seramu", name:"劇場版「美少女戦士セーラームーンEternal」 Q posket-PRINCESS VENUS-", search:"セーラーヴィーナス　せーらーヴぃーなす", type:"qpos", price:300, date:"1899-12-30", img:"images/seramu/vina_qpos_a.jpg", source:"https://bsp-prize.jp/"},
{series:"seramu", name:"劇場版「美少女戦士セーラームーンEternal」 Q posket-PRINCESS VENUS-", search:"セーラーヴィーナス　せーらーヴぃーなす", type:"qpos", price:300, date:"1899-12-30", img:"images/seramu/vina_qpos_b.jpg", source:"https://bsp-prize.jp/"},
{series:"uruse", name:"うる星やつらアニメver. Q posket-LUM-Ⅲ", search:"らむ", type:"qpos", price:300, date:"1899-12-30", img:"images/uruse/qpos3_a.jpg", source:"https://bsp-prize.jp/"},
{series:"uruse", name:"うる星やつらアニメver. Q posket-LUM-Ⅲ", search:"らむ", type:"qpos", price:300, date:"1899-12-30", img:"images/uruse/qpos3_b.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～ハローキティ・ディアダニエル～", search:"でぃあだにえる", type:"", price:600, date:"2026-06-11", img:"images/sanrio/dani_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～ハローキティ・ディアダニエル～", search:"はろーきてぃ", type:"", price:600, date:"2026-06-11", img:"images/sanrio/kite_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"mar", name:"MARVELACT/CUTプレミアムフィギュア“ウルヴァリン", search:"うるヴぁりん", type:"act", price:800, date:"1899-12-30", img:"images/mar/uru_act.jpg", source:"https://segaplaza.jp/"},
{series:"spy", name:"「SPY×FAMILY」 Luminasta (アーニャ・フォージャー) おでけけ ばーじょん2 ", search:"あーにゃふぉーじゃー", type:"lum", price:800, date:"1899-12-30", img:"images/spy/odekeke2.jpg", source:"https://segaplaza.jp/"},
{series:"zigoku", name:"地獄楽 VIBRATION STARS-亜左 弔兵衛-", search:"あざちょうべい", type:"vib", price:500, date:"1899-12-30", img:"images/zigoku/aza_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"zigoku", name:"地獄楽 VIBRATION STARS-山田浅ェ門 士遠-", search:"やまだあさえもんしおん", type:"vib", price:400, date:"1899-12-30", img:"images/zigoku/sion_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"yugi", name:"遊戯王カードゲーム　Equal Arts 青眼の究極竜", search:"ぶるーあいずあるてぃめっとどらごん", type:"equ", price:500, date:"1899-12-30", img:"images/yugi/aru_equ.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"rezero", name:"Re:ゼロから始める異世界生活　Coreful フィギュア　レム～猫耳メイドver.～", search:"れむ　ねこみみめいど", type:"core", price:1400, date:"1899-12-30", img:"images/rezero/remu_core_nekomeido.jpg", source:"https://www.taito.co.jp/"},
{series:"miku", name:"桜ミク　AMP＋ フィギュア～桜ドレスver.～（タイクレ限定）", search:"初音ミク　はつねみく　さくらどれす", type:"amp", price:1600, date:"1899-12-30", img:"images/miku/sakuradoresu_taikure.jpg", source:"https://www.taito.co.jp/"},
{series:"naruto", name:"NARUTO-ナルト- NARUTOP99 うずまきナルトフィギュア", search:"うずまきなると", type:"99", price:1000, date:"1899-12-30", img:"images/naruto/naruto_99.jpg", source:"https://bsp-prize.jp/"},
{series:"naruto", name:"NARUTO-ナルト- NARUTOP99 波風ミナトフィギュア", search:"なみかぜみなと", type:"99", price:1300, date:"1899-12-30", img:"images/naruto/minato_99.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース GLITTER&GLAMOURS-CARROT-", search:"きゃろっと　キャロット", type:"gli", price:600, date:"1899-12-30", img:"images/wanpi/caro_gli_a.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース GLITTER&GLAMOURS-CARROT-", search:"きゃろっと　キャロット", type:"gli", price:600, date:"1899-12-30", img:"images/wanpi/caro_gli_b.jpg", source:"https://bsp-prize.jp/"},
{series:"aobuta", name:"「青春ブタ野郎」シリーズYumemirize‐桜島麻衣‐バニー", search:"さくらじままい", type:"yume", price:700, date:"2026-06-12", img:"images/aobuta/bani_yume.jpg", source:"https://segaplaza.jp/"},
{series:"furi-ren", name:"葬送のフリーレンLuminasta“フリーレン”～葬送のフリーレン～", search:"そうそうのふりーれん", type:"lum", price:1000, date:"2026-06-12", img:"images/furi-ren/furi_tue_lum.jpg", source:"https://segaplaza.jp/"},
{series:"hiro", name:"僕のヒーローアカデミア MAXIMATIC ERASER HEAD", search:"いれいざーへっど", type:"ma", price:500, date:"2026-06-11", img:"images/hiro/ire_ma.jpg", source:"https://bsp-prize.jp/"},
{series:"aimasu", name:"学園アイドルマスター ESPRESTO-Heart bouquet-藤田ことね", search:"ふじたことね", type:"esp", price:600, date:"2026-06-11", img:"images/aimasu/kotone_esp_h.jpg", source:"https://bsp-prize.jp/"},
{series:"naruto", name:"NARUTO-ナルト- 疾風伝 VIBRATION STARS-YAKUSHI KABUTO-", search:"やくしかぶと　薬師カブト", type:"vib", price:700, date:"2026-06-11", img:"images/naruto/kabuto_vib.jpg", source:"https://bsp-prize.jp/"},
{series:"naruto", name:"NARUTO-ナルト- 疾風伝 VIBRATION STARS-UCHIHA ITACHI-Ⅲ", search:"うちはイタチ　うちはいたち", type:"vib", price:800, date:"2026-06-11", img:"images/naruto/itati_vib3.jpg", source:"https://bsp-prize.jp/"},
{series:"tora", name:"To LOVEる-とらぶる-ダークネス GLITTER&GLAMOURS ララ・サタリン・デビルーク", search:"ららさたりんでびるーく", type:"gli", price:600, date:"1899-12-30", img:"images/tora/rara_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】　Coreful フィギュア　アイ～B小町ver.～", search:"あい　びーこまち", type:"core", price:600, date:"2026-06-13", img:"images/osinoko/ai_b_core.jpg", source:"https://www.taito.co.jp/"},
{series:"ante", name:"DELTARUNE フィグライフ! ルールノー・カァドー", search:"るーるのーかぁどー", type:"figl", price:600, date:"2026-06-09", img:"images/ante/ruru_figl.jpg", source:"https://bsp-prize.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 フィギュアライト 猗窩座-破壊殺-", search:"あかざ　はかいさつ", type:"", price:500, date:"2026-06-09", img:"images/kimetu/hakai_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"tensura", name:"転生したらスライムだった件 ESPRESTO-Threefold union-悪魔ディアブロ", search:"あくまでぃあぶろ", type:"esp", price:700, date:"2026-06-09", img:"images/tensura/dea_esp.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボールZ History Box ミスター・サタン", search:"みすたーさたん", type:"his", price:600, date:"2026-06-09", img:"images/db/satan_his.jpg", source:"https://bsp-prize.jp/"},
{series:"deara", name:"デート・ア・ライブ -Relax time-時崎狂三", search:"ときさきくるみ", type:"relax", price:600, date:"2026-06-09", img:"images/deara/kurumi_relax.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース Grandista-JEWELRY.BONNEY-", search:"じゅえりーぼにー　ジュエリーボニー", type:"gra", price:800, date:"2026-06-09", img:"images/wanpi/boni_gra.jpg", source:"https://bsp-prize.jp/"},
{series:"vsupo", name:"ぶいすぽっ！スケールフィギュア-Play with paint-vol.9", search:"小森めと　こもりめと", type:"", price:800, date:"2026-05-22", img:"images/vsupo/meto_gigo.jpg", source:"https://www.gigo.co.jp/prizes"},
{series:"furi-ren", name:"葬送のフリーレンLuminasta“フリーレン”～花畑～", search:"ふりーれん", type:"lum", price:1000, date:"1899-12-30", img:"images/furi-ren/furi_hana_lum.jpg", source:"https://segaplaza.jp/"},
{series:"db", name:"ドラゴンボールDAIMA ベジータ（ミニ） パネル付きフィギュア", search:"べじーた", type:"", price:300, date:"1899-12-30", img:"images/db/bezi_da.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボールDAIMA ゴマー パネル付きフィギュア", search:"ごまー", type:"", price:300, date:"1899-12-30", img:"images/db/goma_da.jpg", source:"https://bsp-prize.jp/"},
{series:"madomagi", name:"魔法少女まどか☆マギカ ソウルジェムキャニスター2", search:"そうるじぇむ", type:"", price:600, date:"1899-12-30", img:"images/madomagi/zyemu_ma.jpg", source:"https://www.sk-japan.co.jp/charatoru/topic"},
{series:"madomagi", name:"魔法少女まどか☆マギカ ソウルジェムキャニスター2", search:"そうるじぇむ", type:"", price:600, date:"1899-12-30", img:"images/madomagi/zyemu_ho.jpg", source:"https://www.sk-japan.co.jp/charatoru/topic"},
{series:"madomagi", name:"魔法少女まどか☆マギカ ソウルジェムキャニスター2", search:"そうるじぇむ", type:"", price:600, date:"1899-12-30", img:"images/madomagi/zyemu_mami.jpg", source:"https://www.sk-japan.co.jp/charatoru/topic"},
{series:"madomagi", name:"魔法少女まどか☆マギカ ソウルジェムキャニスター2", search:"そうるじぇむ", type:"", price:600, date:"1899-12-30", img:"images/madomagi/zyemu_sa.jpg", source:"https://www.sk-japan.co.jp/charatoru/topic"},
{series:"madomagi", name:"魔法少女まどか☆マギカ ソウルジェムキャニスター2", search:"そうるじぇむ", type:"", price:600, date:"1899-12-30", img:"images/madomagi/zyemu_kyo.jpg", source:"https://www.sk-japan.co.jp/charatoru/topic"},
{series:"sera", name:"劇場版「美少女戦士セーラームーンEternal」 GLITTER&GLAMOURS-SUPER SAILOR URANUS-", search:"スーパーセーラーウラヌス　すーぱーせーらーうらぬす", type:"gli", price:1400, date:"1899-12-30", img:"images/seramu/ura_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"sakura", name:"カードキャプターさくら～クリアカード編～　ルームランプ　夢の杖", search:"ゆめのつえ", type:"", price:700, date:"2026-01-30", img:"images/sakura/yumenotue.jpg", source:"https://www.taito.co.jp/"},
{series:"dorakue", name:"ドラゴンクエスト　AM　伝説の魔王フィギュア　シドー", search:"でんせつのまおう　しどー", type:"", price:300, date:"2025-10-25", img:"images/dorakue/sido.jpg", source:"https://www.taito.co.jp/"},
{series:"oba", name:"BiCute Ribbons Figureー シャルティア ー", search:"しゃるてぃあ", type:"ribon", price:700, date:"2026-06-04", img:"images/oba/syaru_ribon.jpg", source:"https://charahiroba.com/"},
{series:"piku", name:"ピクミン青ピクミン水鉄砲", search:"あおぴくみん", type:"", price:300, date:"1899-12-30", img:"images/piku/ao.jpg", source:""},
{series:"mario", name:"スーパーマリオヨッシー水鉄砲", search:"よっしー", type:"", price:300, date:"1899-12-30", img:"images/mario/yosimizu.jpg", source:""},
{series:"mario", name:"スーパーマリオヨッシー水鉄砲", search:"よっしー", type:"", price:300, date:"1899-12-30", img:"images/mario/yosimizu_b.jpg", source:""},
{series:"rerugan", name:"とある科学の超電磁砲TLuminasta“御坂美琴”～大精霊☆メイド～", search:"みさかみこと", type:"lum", price:700, date:"1899-12-30", img:"images/rerugan/mikoto_meido_lum.jpg", source:"https://segaplaza.jp/"},
{series:"miku", name:"HATSUNE MIKU Holiday Memories -ゴルフ-", search:"はつねみく　初音ミク　ごるふ", type:"", price:400, date:"1899-12-30", img:"images/miku/gorufu.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"HATSUNE MIKU Holiday Memories -登山-", search:"はつねみく　初音ミク　とざん", type:"", price:600, date:"1899-12-30", img:"images/miku/tozan.jpg", source:"https://bsp-prize.jp/"},
{series:"rezero", name:"Re:ゼロから始める異世界生活 Luminasta “エミリア” -ことりあそび-", search:"えみりあ", type:"lum", price:800, date:"1899-12-30", img:"images/rezero/emi_kotori.jpg", source:"https://segaplaza.jp/"},
{series:"rezero", name:"Re:ゼロから始める異世界生活　プレシャスフィギュア レム～スバルくんのジャージver.～Renewal", search:"れむ", type:"", price:500, date:"1899-12-30", img:"images/rezero/remu_subaru.jpg", source:"https://www.taito.co.jp/"},
{series:"rezero", name:"Re:ゼロから始める異世界生活 プレシャスフィギュア レム～マリンルックver.～Renewal", search:"れむ", type:"", price:500, date:"1899-12-30", img:"images/rezero/remu_pure_marin.jpg", source:"https://www.taito.co.jp/"},
{series:"rezero", name:"Re:ゼロから始める異世界生活 Luminasta “ラム” -にゃつの日-", search:"らむ", type:"lum", price:400, date:"1899-12-30", img:"images/rezero/ramu_nya.jpg", source:"https://segaplaza.jp/"},
{series:"rezero", name:"Re:ゼロから始める異世界生活 BiCute Bunnies Figureーラム・チャイナ・アンティークver.ー", search:"らむ", type:"bani", price:400, date:"2023-05-13", img:"images/rezero/ramu_bani_chaina.jpg", source:"https://charahiroba.com/"},
{series:"rezero", name:"SSSフィギュア－レム in Arabian Night Another Color ver.－", search:"れむ", type:"", price:500, date:"2022-12-24", img:"images/rezero/remu_ara.jpg", source:"https://charahiroba.com/"},
{series:"rezero", name:"SSSフィギュア－ラム in Arabian Night Another Color ver.－", search:"らむ", type:"", price:300, date:"2022-12-24", img:"images/rezero/ramu_ara.jpg", source:"https://charahiroba.com/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 MAXIMATIC THE MITSURI KANROJI", search:"甘露寺密璃　かんろじみつり", type:"ma", price:1400, date:"1899-12-30", img:"images/kimetu/mituri_ma.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース KING OF ARTIST ROB LUCCI Awakening-SPECIAL ver.-", search:"ろぶるっち　ロブルッチ", type:"koa", price:600, date:"2026-06-03", img:"images/wanpi/rutti_koa_sp.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"サルゲッチュ モニタートップフィギュア～ピポサル～", search:"ぴぽざる", type:"moni", price:500, date:"2026-06-03", img:"images/sonota/saru_pure.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"サルゲッチュ モニタートップフィギュア～ピポサル～", search:"ぴぽざる", type:"moni", price:500, date:"2026-06-03", img:"images/sonota/saru_pure2.jpg", source:"https://bsp-prize.jp/"},
{series:"zyuzyutu", name:"呪術廻戦懐玉・玉折FIGURIZMα“五条悟”術式反転「赫」", search:"ごじょうさとる", type:"fig", price:1100, date:"1899-12-30", img:"images/zyuzyutu/aka_fig.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 VIBRATION STARS PLUS-竈門炭治郎-", search:"かまどたんじろう", type:"vib", price:1300, date:"1899-12-30", img:"images/kimetu/tan_vib_p.jpg", source:"https://bsp-prize.jp/"},
{series:"tyen", name:"チェンソーマン おおきなSOFVIMATES～ポチタは泣きながら俺を待っていた～", search:"ぽちた", type:"sof", price:5000, date:"1899-12-30", img:"images/tyen/potita_naki.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん -俺のフィギュア 野原ひろし-", search:"のはらひろし", type:"", price:800, date:"1899-12-30", img:"images/kuresin/hirosi.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース フィグライフ! モンキー・D・ルフィ-ギア5-vol.3", search:"にか　ニカ　ルフィ　るふぃ", type:"figl", price:1000, date:"1899-12-30", img:"images/wanpi/nika_figl3.jpg", source:"https://bsp-prize.jp/"},
{series:"sakamoto", name:"SAKAMOTODAYSLuminasta“坂本太郎”本気Ver.", search:"さかもとたろう", type:"lum", price:400, date:"1899-12-30", img:"images/sakamoto/sakamoto_honki_lum.jpg", source:"https://segaplaza.jp/"},
{series:"db", name:"ドラゴンボール超 BLOOD OF SAIYANS-ゴジータ&ベジット-", search:"ごじーた", type:"blood", price:500, date:"1899-12-30", img:"images/db/gozi_blood.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 BLOOD OF SAIYANS-ゴジータ&ベジット-", search:"べじっと", type:"blood", price:600, date:"1899-12-30", img:"images/db/bezitto_blood.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 BLOOD OF SAIYANS-ベジータ-", search:"べじーた", type:"blood", price:600, date:"1899-12-30", img:"images/db/bezi_blood.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 MATCH MAKERS 超サイヤ人ゴッド孫悟空（VSビルス）", search:"そんごくう", type:"mat", price:500, date:"1899-12-30", img:"images/db/goku_mat_birusu.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"ドラゴンボール超 MATCH MAKERS ビルス（VS超サイヤ人ゴッド孫悟空）", search:"びるす", type:"mat", price:500, date:"1899-12-30", img:"images/db/birusu_mat_goku.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～SPECIAL MONKEY.D.GARP", search:"モンキーディーガープ　もんきーでぃーがーぷ", type:"dxf", price:800, date:"1899-12-30", img:"images/wanpi/gapu_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～SPECIAL NEFELTARI VIVI", search:"ネフェルタリビビ　ねふぇるたりびび", type:"dxf", price:500, date:"1899-12-30", img:"images/wanpi/bibi_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～SPECIAL MONKEY.D.LUFFY", search:"るふぃ　ルフィ", type:"dxf", price:700, date:"1899-12-30", img:"images/wanpi/rufi_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"pro", name:"プロジェクトセカイカラフルステージ！feat.初音ミク Desktop×DecorateCollections “天馬咲希”", search:"てんまさき", type:"ddc", price:650, date:"1899-12-30", img:"images/pro/tenma_ddc.jpg", source:"https://segaplaza.jp/"},
{series:"wanpi", name:"ワンピース Q posket-ヤマト-", search:"やまと", type:"qpos", price:300, date:"1899-12-30", img:"images/wanpi/yamato_qpos.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース フィグライフ! モンキー・D・ルフィ-ギア5-vol.2", search:"にか　ニカ　ルフィ　るふぃ", type:"figl", price:800, date:"1899-12-30", img:"images/wanpi/nika_figl2.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～JEWELRY.BONNEY CHILDREN ver.", search:"ジュエリーボニー　じゅえりーぼにー", type:"dxf", price:400, date:"1899-12-30", img:"images/wanpi/boni_dxf_child.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"『ONE PIECE FILM RED』 Q posket-UTA-", search:"ウタ　うた", type:"qpos", price:300, date:"1899-12-30", img:"images/wanpi/uta_qpos.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"『ONE PIECE FILM RED』 DXF～THE GRANDLINE LADY～vol.1", search:"ウタ　うた", type:"dxf", price:400, date:"1899-12-30", img:"images/wanpi/uta_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"『ONE PIECE FILM RED』 DXF～THE GRANDLINE SERIES～UTA CHILDREN", search:"ウタ　うた", type:"dxf", price:300, date:"1899-12-30", img:"images/wanpi/uta_dxf_child.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース サボ ルームライト-火拳（ヒケン）-", search:"さぼ　ひけん", type:"", price:400, date:"1899-12-30", img:"images/wanpi/hiken_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース トラファルガー・ロー ルームライト-R・ROOM“凪（サイレント）”-", search:"とらふぁるがーろー　るーむさいれんと", type:"", price:500, date:"1899-12-30", img:"images/wanpi/sairento_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん おおきなSOFVIMATES～野原しんのすけ（ワニ山さんver.）～パステルカラーver.", search:"のはらしんのすけ", type:"sof", price:500, date:"1899-12-30", img:"images/kuresin/wani_sof.jpg", source:"https://bsp-prize.jp/"},    
{series:"osinoko", name:"【推しの子】 全力造形 フィギュア MEMちょ", search:"めむちょ", type:"zenryoku", price:300, date:"1899-12-30", img:"images/osinoko/memu_zen.jpg", source:"http://www.fans.co.jp/"},
{series:"oba", name:"オーバーロード　Desktop Cute フィギュア　アルベド～牛柄水着ver.～Renewal", search:"あるべど", type:"desk", price:500, date:"1899-12-30", img:"images/oba/aru_usi_re.jpg", source:"https://www.taito.co.jp/"},
{series:"wanpi", name:"ワンピース BATTLE RECORD COLLECTION-MONKEY.D.GARP-", search:"もんきーでぃーがーぷ　モンキーディーガープ", type:"bato", price:600, date:"1899-12-30", img:"images/wanpi/gapu_bato1.jpg", source:"https://bsp-prize.jp/"},
{series:"crazy", name:"Crazy Raccoon デスクトップフィギュア-VanilLa-", search:"ばにら　バニラ", type:"moni", price:400, date:"1899-12-30", img:"images/crazy/banira.jpg", source:"https://bsp-prize.jp/"},
{series:"crazy", name:"Crazy Raccoon デスクトップフィギュア-VanilLa-", search:"ばにら　バニラ", type:"moni", price:400, date:"1899-12-30", img:"images/crazy/banira_b.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～ポムポムプリン リラックスver.～", search:"ぽむぽむぷりん", type:"sof", price:500, date:"1899-12-30", img:"images/sanrio/pom_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"togen", name:"桃源暗鬼 むっくんスピーカー", search:"", type:"", price:500, date:"1899-12-30", img:"images/togen/mukkun.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～ポチャッコ リラックスver.～", search:"ぽちゃっこ", type:"sof", price:600, date:"1899-12-30", img:"images/sanrio/po_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"Netflixシリーズ「My Melody & Kuromi」 Fluffy Puffy～My Melody & Kuromi～", search:"くろみ", type:"flu", price:700, date:"1899-12-30", img:"images/sanrio/kuro_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～ハローキティ＆シナモロール～", search:"はろーきてぃ", type:"flu", price:800, date:"1899-12-30", img:"images/sanrio/kitesina_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～ハローキティ＆シナモロール～", search:"しなもろーる", type:"flu", price:800, date:"1899-12-30", img:"images/sanrio/sinakite_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～マイメロディ＆クロミ～", search:"まいめろでぃ", type:"flu", price:600, date:"1899-12-30", img:"images/sanrio/maikuro_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ Fluffy Puffy～マイメロディ＆クロミ～", search:"くろみ", type:"flu", price:700, date:"1899-12-30", img:"images/sanrio/kuromai_flu.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_a.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_b.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_c.jpg", source:"https://bsp-prize.jp/"},
{series:"db", name:"DRAGON BALL SPIRITFLICKS 01", search:"孫悟空　そんごくう", type:"spi", price:600, date:"1899-12-30", img:"images/db/goku_spi_d.jpg", source:"https://bsp-prize.jp/"},
{series:"holo", name:"ホロライブプロダクション ひっかけフィギュアVol.11", search:"不知火フレア　しらぬいふれあ", type:"hikkake", price:200, date:"1899-12-30", img:"images/holo/furea_11.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブプロダクション ひっかけフィギュアVol.11", search:"白銀ノエル　しろがねのえる", type:"hikkake", price:300, date:"1899-12-30", img:"images/holo/noeru_11.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブプロダクション ひっかけフィギュアVol.11", search:"博衣こより　はくいこより", type:"hikkake", price:200, date:"1899-12-30", img:"images/holo/koyori_11.jpg", source:"https://charahiroba.com/"},
{series:"mar", name:"MARVELACT/CUTプレミアムフィギュア“シング”", search:"しんぐ", type:"act", price:400, date:"1899-12-30", img:"images/mar/thing_act.jpg", source:"https://segaplaza.jp/"},
{series:"furi-ren", name:"葬送のフリーレン フィギュアライト フリーレン-ゾルトラーク-", search:"ふりーれん　ぞるとらーく", type:"", price:800, date:"1899-12-30", img:"images/furi-ren/furizoru_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"wnapi", name:"ワンピース THE出航-NAMI-ver.EGGHEAD", search:"なみ", type:"syukko", price:800, date:"1899-12-30", img:"images/wanpi/nami_syukko_egg.jpg", source:"https://bsp-prize.jp/"},
{series:"amagamisan", name:"甘神さんちの縁結び　Coreful フィギュア　甘神夜重", search:"あまがみやえ", type:"core", price:300, date:"1899-12-30", img:"images/amagamisan/yae_core.jpg", source:"https://www.taito.co.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“江戸川コナン”", search:"えどがわこなん", type:"peti", price:400, date:"1899-12-30", img:"images/konan/konan_peti.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“灰原哀”", search:"はいばらあい", type:"peti", price:400, date:"1899-12-30", img:"images/konan/ai_peti.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“工藤新一”", search:"くどうしんいち", type:"peti", price:400, date:"1899-12-30", img:"images/konan/sin_peti.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナンPetiteWorldMemoriesミニフィギュア“毛利蘭”", search:"もうりらん", type:"peti", price:400, date:"1899-12-30", img:"images/konan/ran_peti.jpg", source:"https://segaplaza.jp/"},
{series:"gotoyome", name:"五等分の花嫁＊ 中野一花フィギュア五等分の花嫁アニメ原画展ver.", search:"なかのいちか", type:"", price:300, date:"1899-12-30", img:"images/gotoyome/itika_genga.jpg", source:"https://bsp-prize.jp/"},
{series:"oba", name:"オーバーロード IF-Relax time-アルベド", search:"あるべど", type:"relax", price:600, date:"1899-12-30", img:"images/oba/aru_relax_if.jpg", source:"https://bsp-prize.jp/"},
{series:"sasa", name:"ささやくように恋を唄うちょこのせプレミアムフィギュア“朝凪依”", search:"あさなぎより", type:"tyoko", price:300, date:"1899-12-30", img:"images/sasa/asa_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"sasa", name:"ささやくように恋を唄うちょこのせプレミアムフィギュア“木野ひまり”", search:"きのひまり", type:"tyoko", price:300, date:"1899-12-30", img:"images/sasa/kino_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 フィギュアライト 冨岡義勇-水の呼吸-", search:"とみおかぎゆう　みずのこきゅう", type:"", price:500, date:"2026-06-04", img:"images/kimetu/giyu_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"death", name:"DEATH NOTE　ぬーどるストッパーフィギュアーLー", search:"える　", type:"nusuto", price:700, date:"2026-06-05", img:"images/death/l_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"wanpi", name:"ワンピース BATTLE RECORD COLLECTION-BARTHOLOMEW.KUMA-", search:"バーソロミューくま　ばーそろみゅーくま", type:"", price:600, date:"2026-06-03", img:"images/wanpi/kuma_bato.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"初音ミク　Trio-Try-iT Figureーレイニーダンスー", search:"はつねみく　れいにーだんす", type:"trio", price:600, date:"2026-06-04", img:"images/miku/ame_trio.jpg", source:"https://charahiroba.com/"},
{series:"db", name:"ドラゴンボール超 SOLID EDGE WORKS-THE出陣-ゴールデンフリーザ", search:"ごーるでんふりーざ", type:"syutu", price:600, date:"2026-06-03", img:"images/db/gorufuri_syutu.jpg", source:"https://bsp-prize.jp/"},
{series:"dorakue", name:"ドラゴンクエスト　AM　ポケットティッシュケース　ミイラ男＆マミー", search:"みいらおとこ", type:"", price:800, date:"2026-05-23", img:"images/dorakue/mira_a.jpg", source:"https://www.taito.co.jp/"},
{series:"dorakue", name:"ドラゴンクエスト　AM　ポケットティッシュケース　ミイラ男＆マミー", search:"まみー", type:"", price:800, date:"2026-05-23", img:"images/dorakue/mira_b.jpg", source:"https://www.taito.co.jp/"},
{series:"vsupo", name:"ぶいすぽっ！スケールフィギュア-Play with paint-vol.9", search:"夢野あかり　ゆめのあかり", type:"", price:800, date:"2026-05-22", img:"images/vsupo/akari_gigo.jpg", source:"https://www.gigo.co.jp/prizes"},
{series:"konan", name:"名探偵コナンちょこのせプレミアムフィギュア“怪盗キッド”～寝そべりVer.～", search:"かいとうきっど", type:"tyoko", price:600, date:"1899-12-30", img:"images/konan/kiddo_ne_tyoko.jpg", source:"https://segaplaza.jp/"},
{series:"mazyotabi", name:"魔女の旅々　Desktop Cute フィギュア　イレイナ～私服ver.～Renewal", search:"いれいな", type:"desk", price:800, date:"1899-12-30", img:"images/mazyotabi/sifuku_desk_re.jpg", source:"https://www.taito.co.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～ララ～", search:"らら", type:"sof", price:500, date:"1899-12-30", img:"images/sanrio/rara_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ SOFVIMATES～キキ～", search:"きき", type:"sof", price:500, date:"1899-12-30", img:"images/sanrio/kiki_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"haikyu", name:"ハイキュー‼ すやすやルームライト-日向翔陽-", search:"ひなたしょうよう", type:"", price:800, date:"1899-12-30", img:"images/haikyu/hinata_rumu.jpg", source:"https://bsp-prize.jp/"},
{series:"ozya", name:"おジャ魔女どれみ Paldolce collection Grande-春風どれみ-", search:"はるかぜどれみ", type:"", price:300, date:"1899-12-30", img:"images/ozya/doremi.jpg", source:"https://bsp-prize.jp/"},
{series:"gegege", name:"映画「鬼太郎誕生 ゲゲゲの謎」　Vivitフィギュア ねこ娘", search:"ねこむすめ", type:"vivi", price:300, date:"1899-12-30", img:"images/gegege/neko_vivi.jpg", source:"http://www.fans.co.jp/"},
{series:"nyanko", name:"にゃんこ大戦争 にゃんこ軍団出陣フィギュア～超極ネコ祭 厄災の子キャスリィ～", search:"やくさいのこきゃすりぃ", type:"", price:500, date:"1899-12-30", img:"images/nyanko/kyasu.jpg", source:"https://bsp-prize.jp/"},
{series:"pawapuro", name:"パワフルプロ野球&プロ野球スピリッツ プライズボブルヘッドコレクション", search:"パワプロくん　ぱわぷろくん", type:"", price:500, date:"2026-05-28", img:"images/pawapuro/pawa_bobu.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"pawapuro", name:"パワフルプロ野球&プロ野球スピリッツ プライズボブルヘッドコレクション", search:"ちょうしくん　調子くん", type:"", price:500, date:"2026-05-28", img:"images/pawapuro/tyousi_bobu.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"zyuzyutu", name:"呪術廻戦 KING OF ARTIST GOJO・GETO-懐玉・玉折-SPECIAL ver.", search:"げとうすぐる　夏油傑", type:"koa", price:1100, date:"1899-12-30", img:"images/zyuzyutu/geto_koa_sp.jpg", source:"https://bsp-prize.jp/"},
{series:"kaizyu", name:"怪獣８号　TOONIZEー怪獣８号ー", search:"かいじゅう8ごう", type:"", price:400, date:"1899-12-30", img:"images/kaizyu/kaizyu_too_a.jpg", source:"https://charahiroba.com/"},
{series:"tensura", name:"転生したらスライムだった件 EXQ フィギュア～リムル＝テンペスト～-metallic color version-", search:"りむるてんぺすと", type:"exq", price:1000, date:"1899-12-30", img:"images/tensura/rimuru_exq_namco.jpg", source:"https://bsp-prize.jp/"},
{series:"puniru", name:"Trio-Try-iT Figure ー いつものかわいいぷにる ー", search:"", type:"trio", price:400, date:"1899-12-30", img:"images/puniru/puniru_trio.jpg", source:"https://charahiroba.com/"},
{series:"deara", name:"デート・ア・ライブV BiCute Bunnies Figureー星宮六喰ー", search:"ほしみやむくろ", type:"bani", price:500, date:"1899-12-30", img:"images/deara/mukuro_bani.jpg", source:"https://charahiroba.com/"},
{series:"dandadan", name:"TVアニメ『ダンダダン』Luminasta “モモ”Vol.2Ver.1.5", search:"もも", type:"lum", price:500, date:"1899-12-30", img:"images/dandadan/momo_lum1.5.jpg", source:"https://segaplaza.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ネネちゃんと", search:"野原しんのすけ　のはらしんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinnene_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ネネちゃんと", search:"ネネちゃん　ねねちゃん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/nenesin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ボーちゃんと", search:"野原しんのすけ　のはらしんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinbou_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～ボーちゃんと", search:"ボーちゃん　ぼーちゃん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/bousin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～風間くんと", search:"のはらしんのすけ　野原しんのすけ", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/sinkaza_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん しんちゃんとなかよしメモリーズ～幼稚園にいくゾ～風間くんと", search:"風間くん　かざまくん", type:"nakayosi", price:600, date:"1899-12-30", img:"images/kuresin/kazasin_you.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～へびしんちゃんとうましんちゃん～", search:"のはらしんのすけ　野原しんのすけ", type:"", price:500, date:"1899-12-30", img:"images/kuresin/hebi.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュア～へびしんちゃんとうましんちゃん～", search:"のはらしんのすけ　野原しんのすけ", type:"", price:500, date:"1899-12-30", img:"images/kuresin/uma.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ Q posket-佐野万次郎-私服ver.", search:"さのまんじろう　マイキー　まいきー", type:"qpos", price:300, date:"1899-12-30", img:"images/toribe/maiki_qpos_sifuku.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ Q posket-佐野万次郎-私服ver.", search:"さのまんじろう　マイキー　まいきー", type:"qpos", price:300, date:"1899-12-30", img:"images/toribe/maiki_qpos_sifuku_b.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース THE出航-SABO-", search:"サボ　さぼ", type:"syukko", price:500, date:"1899-12-30", img:"images/wanpi/sabo1_syukko.jpg", source:"https://bsp-prize.jp/"},
{series:"spy", name:"SPY×FAMILY Q posket-アーニャ・フォージャー-Ⅲ", search:"あーにゃふぉーじゃー", type:"qpos", price:300, date:"1899-12-30", img:"images/spy/anya3_qpos.jpg", source:"https://bsp-prize.jp/"},
{series:"spy", name:"SPY×FAMILY Q posket-アーニャ・フォージャー-Ⅲ", search:"あーにゃふぉーじゃー", type:"qpos", price:300, date:"1899-12-30", img:"images/spy/anya3_qpos_b.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース DXF～THE GRANDLINE SERIES～EXTRA KING", search:"キング　きんぐ", type:"dxf", price:600, date:"1899-12-30", img:"images/wanpi/king_dxf.jpg", source:"https://bsp-prize.jp/"},
{series:"aimasu", name:"アイドルマスター ミリオンライブ！-Celestial vivi-如月千早", search:"きさらぎちはや", type:"cele", price:300, date:"1899-12-30", img:"images/aimasu/tihaya_cele.jpg", source:"https://bsp-prize.jp/"},
{series:"toribe", name:"東京リベンジャーズ プレミアムフィギュア“乾青宗”-黒龍-", search:"いぬいせいしゅう", type:"", price:300, date:"1899-12-30", img:"images/toribe/inui.jpg", source:"https://segaplaza.jp/"},
{series:"toribe", name:"東京リベンジャーズ　九井一フィギュア", search:"ここのいはじめ", type:"", price:300, date:"1899-12-30", img:"images/toribe/kokonoi.jpg", source:"https://www.taito.co.jp/"},
{series:"kinniku", name:"キン肉マン サウナフィギュア-テリーマン-", search:"てりーまん", type:"", price:300, date:"1899-12-30", img:"images/kinniku/teri_sauna.jpg", source:"https://bsp-prize.jp/"},
{series:"kinniku", name:"キン肉マン サウナフィギュア-キン肉マン-", search:"きんにくまん", type:"", price:600, date:"1899-12-30", img:"images/kinniku/kin_sauna.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】　Vivitフィギュア アイ チアリーディングVer.", search:"あい", type:"vivi", price:500, date:"1899-12-30", img:"images/osinoko/ai_vivi.jpg", source:"http://www.fans.co.jp/"},
{series:"oba", name:"オーバーロード IFアルベドフィギュア-teacher style ver.-", search:"あるべど", type:"", price:500, date:"1899-12-30", img:"images/oba/aru_tea.jpg", source:"https://bsp-prize.jp/"},
{series:"deara", name:"デート・ア・ライブ GLITTER&GLAMOURS-KURUMI TOKISAKI-", search:"ときさきくるみ", type:"gli", price:400, date:"1899-12-30", img:"images/deara/kurumi_gli.jpg", source:"https://bsp-prize.jp/"},
{series:"witti", name:"TVアニメ『ウィッチウォッチ』　浴衣フィギュア 若月ニコ", search:"わかつきにこ", type:"", price:300, date:"1899-12-30", img:"images/witti/niko_yukata.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"witti", name:"TVアニメ『ウィッチウォッチ』　浴衣フィギュア 宮尾音夢", search:"みやおねむ", type:"", price:300, date:"1899-12-30", img:"images/witti/nemu_yukata.jpg", source:"https://p.eagate.573.jp/game/prize/collection/top/index.html"},
{series:"sao", name:"ソードアート・オンライン BiCute Bunnies Figureーアスナー", search:"あすな", type:"bani", price:600, date:"1899-12-30", img:"images/sao/asuna_bani.jpg", source:"https://charahiroba.com/"},
{series:"100kano", name:"君のことが大大大大大好きな100人の彼女 -Relax time-花園羽香里", search:"はなぞのはかり", type:"relax", price:1000, date:"1899-12-30", img:"images/100kano/hana_relax.jpg", source:"https://bsp-prize.jp/"},
{series:"konosuba", name:"この素晴らしい世界に祝福を！３　Coreful フィギュア　ダクネス～水着ver.～", search:"だくねす", type:"core", price:900, date:"1899-12-30", img:"images/konosuba/daku_core_mizugi.jpg", source:"https://www.taito.co.jp/"},
{series:"spy", name:"SPY×FAMILY　Trio－Try－iT Figureーアーニャ・フォージャーー", search:"あーにゃふぉーじゃー", type:"trio", price:500, date:"1899-12-30", img:"images/spy/anya_trio.jpg", source:"https://charahiroba.com/"},
{series:"kimetu", name:"「鬼滅の刃」　FIGURIZMα　“甘露寺蜜璃”", search:"かんろじみつり", type:"fig", price:1300, date:"1899-12-30", img:"images/kimetu/kanrozi_fig.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"アニメ「鬼滅の刃」 MAXIMATIC THE MITSURI KANROJI", search:"かんろじみつり", type:"ma", price:1700, date:"1899-12-30", img:"images/kimetu/kanrozi_ma.jpg", source:"https://bsp-prize.jp/"},
{series:"botti", name:"アニメ「ぼっち・ざ・ろっく！」 伊地知虹夏 フィギュア vol.2", search:"いじちにじか", type:"", price:600, date:"1899-12-30", img:"images/botti/nizika2.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】　Aqua Float Girls フィギュア　アイ", search:"あい", type:"aqua", price:900, date:"1899-12-30", img:"images/osinoko/ai_aqua.jpg", source:"https://www.taito.co.jp/"},
{series:"atorie", name:"アニメ『ライザのアトリエ ～常闇の女王と秘密の隠れ家～』　Coreful フィギュア　ライザ～水着ver.～", search:"らいざ", type:"core", price:600, date:"1899-12-30", img:"images/atorie/raiza_core_mizugi.jpg", source:"https://www.taito.co.jp/"},
{series:"sonota", name:"勇気爆発バーンブレイバーン Break time collection vol.1", search:"ゆうきばくはつばーんぶれいばーん", type:"bre", price:300, date:"1899-12-30", img:"images/sonota/ban_bre.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース フィグライフ! モンキー・D・ルフィ-ギア5-vol.4", search:"るふぃ　ニカ　にか", type:"figl", price:400, date:"1899-12-30", img:"images/wanpi/nika_figl4.jpg", source:"https://bsp-prize.jp/"},
{series:"osinoko", name:"【推しの子】 アイ-サインはB-フィギュア", search:"あい", type:"", price:600, date:"1899-12-30", img:"images/osinoko/ai_b.jpg", source:"https://bsp-prize.jp/"},
{series:"eva", name:"シン・エヴァンゲリオン劇場版Luminasta“真希波・マリ・イラストリアス”", search:"まきなみまりいらすとりあす", type:"lum", price:800, date:"1899-12-30", img:"images/eva/mari_lum.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"鬼滅の刃 ぬーどるストッパーフィギュア ―伊黒小芭内―", search:"いぐろおばない", type:"nusuto", price:4500, date:"1899-12-30", img:"images/kimetu/iguro_nusuto.jpg", source:"https://charahiroba.com/"},
{series:"zyuzyutu", name:"呪術廻戦懐玉・玉折FIGURIZMα“五条悟”覚醒", search:"ごじょうさとる", type:"fig", price:1300, date:"1899-12-30", img:"images/zyuzyutu/gozyo_kakusei.jpg", source:"https://segaplaza.jp/"},
{series:"kimetu", name:"鬼滅の刃　プレミアムちょこのせフィギュア“煉󠄁獄杏寿郎”", search:"れんごくきょうじゅろう", type:"tyoko", price:800, date:"1899-12-30", img:"images/kimetu/rengoku_tyoko_oni.jpg", source:"https://segaplaza.jp/"},
{series:"mazyotabi", name:"魔女の旅々　AMP＋ イレイナ フィギュア～魔女服ver.～", search:"いれいな", type:"amp", price:1200, date:"2025-01-11", img:"images/mazyotabi/amp.jpg", source:"https://www.taito.co.jp/"},
{series:"naruto", name:"NARUTO-ナルト- BANPRESTO FIGURE COLOSSEUM 造形忍界大戦 ロック・リー", search:"ろっくりー", type:"ninkai", price:2300, date:"1899-12-30", img:"images/naruto/ri_ninkai.jpg", source:"https://bsp-prize.jp/"},
{series:"wanpi", name:"ワンピース THE出航-NAMI-", search:"なみ　ナミ", type:"syukko", price:500, date:"1899-12-30", img:"images/wanpi/nami_syukko.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～マイメロディ・クロミ～", search:"まいめろでぃ", type:"", price:600, date:"2026-05-27", img:"images/sanrio/maimero_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"sanrio", name:"サンリオキャラクターズ コスプレフィギュアコレクション～マイメロディ・クロミ～", search:"くろみ", type:"", price:800, date:"2026-05-27", img:"images/sanrio/kuromi_kosu.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 鎮座獣 コイン怪獣カネゴン", search:"こいんかいじゅうかねごん", type:"tinza", price:400, date:"2026-05-27", img:"images/uru/kane_tinza.jpg", source:"https://bsp-prize.jp/"},
{series:"uru", name:"ウルトラマンシリーズ 鎮座獣 コイン怪獣カネゴン", search:"こいんかいじゅうかねごん", type:"tinza", price:500, date:"2026-05-27", img:"images/uru/kane_tinza_b.jpg", source:"https://bsp-prize.jp/"},
{series:"monhan", name:"モンスターハンター 鎮座獣 アルシュベルド～夢から覚めて～", search:"あるしゅべると", type:"tinza", price:400, date:"2026-05-27", img:"images/monhan/arusyu_tinza.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"Trio-Try-iT Figureージジ(変身)ー", search:"じじ", type:"trio", price:400, date:"2026-05-27", img:"images/dandadan/zizi_trio.jpg", source:"https://charahiroba.com/"},
{series:"umamusume", name:"Trio-Try-iT Figure―ヒシミラクルー", search:"ひしみらくる", type:"trio", price:500, date:"2026-05-27", img:"images/umamusume/hisi_trio.jpg", source:"https://charahiroba.com/"},
{series:"holo", name:"ホロライブ #hololive IF -ホロベイビーズ-宝鐘マリン", search:"ほうしょうまりん", type:"", price:700, date:"2026-05-26", img:"images/holo/marin_baby.jpg", source:"https://bsp-prize.jp/"},
{series:"holo", name:"ホロライブ #hololive IF -ホロベイビーズ-こぼ・かなえる", search:"", type:"", price:700, date:"2026-05-26", img:"images/holo/kobo_baby.jpg", source:"https://bsp-prize.jp/"},
{series:"king", name:"キングダム オギコフィギュア", search:"おぎこ", type:"", price:400, date:"2026-05-27", img:"images/king/ogiko.jpg", source:"https://bsp-prize.jp/"},
{series:"tomuzyeri", name:"トムとジェリー ビッグソフビフィギュア-Yummy Bread-", search:"じぇりー　たふぃー　ジェリー　タフィー", type:"", price:400, date:"2026-05-27", img:"images/tomuzyeri/zyeritafi.jpg", source:"https://bsp-prize.jp/"},
{series:"sonota", name:"UNIVERSAL おおきなSOFVIMATES～おさるのジョージ～", search:"おさるのじょーじ", type:"sof", price:400, date:"2026-05-26", img:"images/sonota/zyozi_sof.jpg", source:"https://bsp-prize.jp/"},
{series:"dandadan", name:"TVアニメ『ダンダダン』 フィグライフ!モモ", search:"もも", type:"figl", price:300, date:"2026-05-26", img:"images/dandadan/momo_figl.jpg", source:"https://bsp-prize.jp/"},
{series:"miku", name:"初音ミクシリーズ　Luminasta　“初音ミク 16th Anniversary”KEI Ver.", search:"はつねみく", type:"lum", price:700, date:"1899-12-30", img:"images/miku/16_key.jpg", source:"https://segaplaza.jp/"},
{series:"db", name:"ドラゴンボールZ MATCH MAKERS 魔人ブウ（VS超サイヤ人3孫悟空）", search:"まじんぶう", type:"mat", price:600, date:"1899-12-30", img:"images/db/bu_mat_goku.jpg", source:"https://bsp-prize.jp/"},
{series:"king", name:"キングダム Grandistaｰ桓騎ｰ", search:"かんき", type:"gra", price:500, date:"2026-05-27", img:"images/king/kanki_gra.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュアvol.3", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"1899-12-30", img:"images/kuresin/kosu_buri.jpg", source:"https://bsp-prize.jp/"},
{series:"kuresin", name:"クレヨンしんちゃん コスプレしんちゃんフィギュアvol.3", search:"野原しんのすけ　のはらしんのすけ", type:"", price:600, date:"1899-12-30", img:"images/kuresin/kosu_kan.jpg", source:"https://bsp-prize.jp/"},
{series:"konan", name:"名探偵コナン XrossLink フィギュア“江戸川コナン”", search:"えどがわこなん", type:"xros", price:400, date:"1899-12-30", img:"images/konan/konan_xros.jpg", source:"https://segaplaza.jp/"},
{series:"konan", name:"名探偵コナン XrossLink フィギュア“怪盗キッド”", search:"かいとうきっど", type:"xros", price:700, date:"1899-12-30", img:"images/konan/kiddo_xros.jpg", source:"https://segaplaza.jp/"},
{series:"gorukamu", name:"TVアニメ『ゴールデンカムイ』XrossLinkフィギュア“白石由竹”", search:"しらいしよしたけ", type:"xros", price:300, date:"1899-12-30", img:"images/gorukamu/siraisi_xros.jpg", source:"https://segaplaza.jp/"},
];
